### ISSUE TITLE
DD_SITE parameter is not available for the Azure function

### ISSUE THREAD

**Issue by nithril** [DataDog/datadog-serverless-functions#104]
**Describe what happened:**
DD_SITE parameter is not available for the Azure function

**Describe what you expected:**
DD_SITE parameter

**Comment by le-he-hoo** [comment]
Hey @nithril 

Thanks for bringing this up! 

We've just merged a PR that adds a DD_SITE option for the Azure function.  I'll close this out for now, but don't hesitate to reach out to support@datadoghq.com should you run into any issues!
