### ISSUE TITLE
Getting error in lambda_function.phy

### ISSUE THREAD

**Issue by ParthivSavani** [DataDog/datadog-serverless-functions#113]
**Describe what happened:**
Creating new lambda function and trying to test, getting below error:

```
Response:
{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      156,
      "lambda_handler",
      "\"You must configure your API key before starting this lambda function (see #Parameters section)\""
    ]
  ],
  "errorType": "Exception",
  "errorMessage": "You must configure your API key before starting this lambda function (see #Parameters section)"
}
```

If I remove below code and test, getting `null` in the response.
```    # Check prerequisites
    if DD_API_KEY == "<your_api_key>" or DD_API_KEY == "":
        raise Exception(
            "You must configure your API key before starting this lambda function (see #Parameters section)"
        )
    # Check if the API key is the correct number of characters
    if len(DD_API_KEY) != 32:
        raise Exception(
            "The API key is not the expected length. Please confirm that your API key is correct"
        )
```
**Describe what you expected:**
It should be executed successfully without any error. 

**Steps to reproduce the issue:**
I have Configured same datadog API keys in below 2 lines.

1. https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/lambda_function.py#L46
2. https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/lambda_function.py#L154

**Question:**
- I believe it is failing because I am passing the same datadog API key in both the lines. So, What would be the value of 'your_api_key'?

Thanks.

**Comment by NilsBunge** [comment]
Hello @ParthivSavani ,

I'm not sure to understand the situation here.
You have two ways to specify your Datadog Apikey:

- Directly in the code, [there](https://cl.ly/fd43fbe10e97)
- By Using the `DD_API_KEY` environment variables.

Would you mind sharing which one you used?

**Comment by NilsBunge** [comment]
Hello @ParthivSavani,

Just wanted to see if you had a chance to see my comments above.
Let me know if you can provide more information about your setup .

**Comment by NilsBunge** [comment]
I'm going to go ahead and close this issue. Feel free to reach out to support@datadoghq.com if you still have any issue with the Lambda.
