### ISSUE TITLE
Function does not handle s3 events delivered via SNS.

### ISSUE THREAD

**Issue by hauboldj** [DataDog/datadog-serverless-functions#114]
**Describe what happened:**
If you need s3 events to flow to multiple lambda functions you need to send the s3 events to an SNS topic and then subscribe each lambda to the SNS topic.

This function just handles the SNS payload as a structured data, not as an s3 event.
**Describe what you expected:**
This function should detect the s3 event inside the SNS payload and handle the object.

**Steps to reproduce the issue:**
Send s3 event to SNS topic. Subscribe lambda to SNS topic.

**Comment by NilsBunge** [comment]
Hello @hauboldj ,

Thanks for submitting this request.

That's indeed something that should be improved to better support data sent through SNS topic.
We are currently improving the function to better support logs sent through Kinesis and we will make sure to do the same for SNS topics.

Do not hesitate to submit a PR if you have ideas how this could be done.

Once again, thanks for helping improving this Lambda function.

**Comment by tianchu** [comment]
Closing the issue, feel free to track the progress at https://github.com/DataDog/datadog-serverless-functions/pull/351
