### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by katharosada** [DataDog/datadog-serverless-functions#119]
Python 3 is almost 10 years old now, and Python2.7 will be unsupported in a few months time. All the library dependencies on this lambda support Python3 so there should be nothing blocking this upgrade.

**Comment by NilsBunge** [comment]
Hello @katharosada ,

This is a very good point and we should definitely update this function to support python 3.
We will make sure to do this before python 2.7 is unsupported.

**Comment by NilsBunge** [comment]
For tracking, here is the PR for it: https://github.com/DataDog/datadog-serverless-functions/pull/133

**Comment by FnTm** [comment]
@NBParis sorry for resurrecting an issue, but is there any chance RDS Enhanced logging lambda would receive similar love?

**Comment by NilsBunge** [comment]
@FnTm Hello there,

The same Lambda should be used to collect all AWS service logs (including RDS ones) so we should be covered.
However, are you talking about the Lambda that transform RDS logs into metrics? (The one located [here](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/rds_enhanced_monitoring) )

**Comment by FnTm** [comment]
@NBParis Yes, I was referring to the Lambda that transforms RDS logs into metrics. I took a quick look at the code, and it looks like it's 2.x only at the moment (due to things like print statements in the older syntax).

**Comment by NilsBunge** [comment]
Pinging @pinkerton for visibility. Definitely make sense to migrate all the lambda we have to python 3.

**Comment by william-richard** [comment]
Any news about upgrading the RDS lambda to python 3?  Would it make sense to reopen this issue, or start a new one, until the upgrade is complete?
