### ISSUE TITLE
Lambda Log forwarder: Metadata is shared between different logs when using Kinesis as event_type

### ISSUE THREAD

**Issue by Edern** [DataDog/datadog-serverless-functions#122]
**Describe what happened:**
When Lambda logs arrive from Kinesis, each record in the event share the same metadata object as the others. This result in some logs getting tagged with multiple `functionname`.

**Describe what you expected:**
I expect each log to have the proper `functionname` tag

**Steps to reproduce the issue:**
Test the handler with one kinesis event containing multiple lambda logs. See that the resulting logs in Datadog have multiple functionnames.

**Comment by NilsBunge** [comment]
Hello @Edern,

Thanks for reporting this issue.
Seems that we indeed took the same logic than for Cloudwatch triggers that assume that only one Lambda logs will be available per batch.

We will have a look to see how this can be addressed but feel free to submit a PR for this if you already have an idea.

Once again, thanks for helping us improve this log forwarder.

**Comment by tianchu** [comment]
The specific issue for duplicate (wrong) lambda `functionname` tags was fixed https://github.com/DataDog/datadog-serverless-functions/pull/182
