### ISSUE TITLE
Python code is generating a DeprecationWarning

### ISSUE THREAD

**Issue by JmeG** [DataDog/datadog-serverless-functions#136]
**Describe what happened:**
This Python code is generating a DeprecationWarning because it's relying on a vendored requests package.  

https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/lambda_function.py#L14

/opt/python/lib/python2.7/site-packages/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the get() function from 'botocore.vendored.requests'. This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date. We recommend you install the requests package, 'import requests' directly, and use the requests.get() fun
/opt/python/lib/python2.7/site-packages/botocore/vendored/requests/api.py:67: DeprecationWarning: You are using the get() function from 'botocore.vendored.requests'. This is not a public API in botocore and will be removed in the future. Additionally, this version of requests is out of date. We recommend you install the requests package, 'import requests' directly, and use the requests.get() function instead.

**Describe what you expected:**
As described in the above message this code should be using a non-vendored requests package or a different package for generating HTTP requests.

**Steps to reproduce the issue:**
It should be easily reproduced anytime this function is executed.

**Comment by tianchu** [comment]
Thanks for the report! https://github.com/DataDog/datadog-serverless-functions/pull/170 should have it fixed.
