### ISSUE TITLE
Python 3 not compatible with DD_KMS_API_KEY

### ISSUE THREAD

**Issue by pauldraper** [DataDog/datadog-serverless-functions#155]
**Describe what happened:**

Lambda function reports "invalid API key"

**Describe what you expected:**

No error.

**Steps to reproduce the issue:**

Use Python 3.7 with DD_KMS_API_KEY

The string interpolation does not work with the binary value that comes from decrypted DD_KMS_API_KEY.

**Comment by vhiairrassary** [comment]
We just had the same issue with python 3.7. Adding `.decode("utf-8")` to the following code fix the issue:
```
ENCRYPTED = os.environ["DD_KMS_API_KEY"]
DD_API_KEY = boto3.client("kms").decrypt(
    CiphertextBlob=base64.b64decode(ENCRYPTED)
)["Plaintext"]
```

**Comment by vhiairrassary** [comment]
There is already a open PR: https://github.com/DataDog/datadog-serverless-functions/pull/152

**Comment by tianchu** [comment]
https://github.com/DataDog/datadog-serverless-functions/pull/152 is merged
