### ISSUE TITLE
aws/logs_monitoring Adding parameters to SAM template to allow easier automated deployment of the log forwarder

### ISSUE THREAD

**Issue by jamesk322** [DataDog/datadog-serverless-functions#158]
I've managed to setup a near complete "infrastructure as code" deployment of the SAM template which essentially replicates the manual process of using the one click deployment inside of the AWS dashboard but instead executes automatically as part of our terraform initialisation.

The issue I've encountered is that while I can automatically deploy the Lambda & new role to my AWS environments I still have to manually set our `DD_API_KEY` and update the execution role linked to the Lambda.

Ideally instead of this two parameters could be provided to the SAM template
* `DD_API_KEY` which would (if set) be used as an environment variable inside the Lambda
* `EXECUTION_ROLE_ARN` (if set) would override the default execution role which is attached to the Lambda

Both would completely remove the need for any manual setting if, like our team, infrastructure changes are all managed through IAC.

If this sounds like a good addition I'm happy to do all the work and submit a PR, please let me know!

**Comment by raehalme** [comment]
Also would it make sense to publish the function ARN as an Output so that the function can easily be referenced elsewhere?

**Comment by tianchu** [comment]
Do you think this PR would help https://github.com/DataDog/datadog-serverless-functions/pull/171?
