### ISSUE TITLE
DataDog AWS Lambda setting `DD_TAGS=env:none`

### ISSUE THREAD

**Issue by aldegoeij** [DataDog/datadog-serverless-functions#165]
https://github.com/DataDog/datadog-serverless-functions/blob/958a66227c409f03e921c830f5801676b22d6f80/aws/logs_monitoring/lambda_function.py#L803-L806

Why is the `env` tag set to `none`? There is no mechanism provided to set it to something else, and here its being concatted behind DD_TAGS effectively overwriting it.

https://github.com/DataDog/datadog-serverless-functions/blob/958a66227c409f03e921c830f5801676b22d6f80/aws/logs_monitoring/lambda_function.py#L533-L543

What is the correct way to pass and 'environment' tag (e.g. `prod`)?

**Comment by tianchu** [comment]
Hi @aldegoeij, 

Thanks for your feedback, and sorry for the late reply!

It should be now fixed: https://github.com/DataDog/datadog-serverless-functions/pull/175.

FYI, if you set `DD_TAGS` to `env:prod`, and it would NOT be overriden by`env:none`. Both of them would be tagged to the log entries like the screenshot below. You should be able to locate these logs by searching `env:prod` or `env:none` (I know it's annoying).

Datadog tags are often written in a `key:value` format to power search facets, but they are treated as strings internally, which means `env:prod` and `env:none` are two completely different tags.

![image](https://user-images.githubusercontent.com/2373434/68339929-82b0eb00-00b3-11ea-9289-b683eb9b864d.png)

We added tag `env:none` to enable the navigation from the log management UI to the corresponding APM service page, which requires knowing both `service` and `env`. By default, serverless services are tagged with `env:none` in APM.

I'm going to close this issue for now, but feel free to re-open if you find things working differently for you.
