### ISSUE TITLE
Lambda Execution succeeded , but get parsing error

### ISSUE THREAD

**Issue by Mohitg06** [DataDog/datadog-serverless-functions#167]
**Describe what happened:**
Followed: https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring 
 When I ran a test the event, I see Execution succeeded but I get the below error:
Exception while forwarding logs in batch ['{"message": "Error parsing the object. Exception: Event type not supported (see #Event supported section) for event {\'key3\': \'value3\', \'key2\': \'value2\', \'key1\': \'value1\'}",

**Comment by tianchu** [comment]
@Mohitg06 you need to select the `CloudWatch Logs` event for test. Here is the documentation: https://docs.datadoghq.com/integrations/amazon_web_services/?tab=allpermissions#test-your-lambda

Sorry for not being clear on README. Will update it soon.
