### ISSUE TITLE
Latest version of botocore incompatible with log monitoring lambda_function.py

### ISSUE THREAD

**Issue by oltruong** [DataDog/datadog-serverless-functions#168]
**Describe what happened:**

Error while executing log monitoring `lambda_function.py`

**Describe what you expected:**

The following error occurs: `module 'botocore.vendored.requests' has no attribute 'get'`

**Steps to reproduce the issue:**

Use boto3 version `1.10.0` whose botocore version is `1.13.0`

**Comment by tianchu** [comment]
Thanks for the report and PR! We have been working this issue too:  https://github.com/DataDog/datadog-serverless-functions/pull/170
