### ISSUE TITLE
Forward tags from upstream sources

### ISSUE THREAD

**Issue by PurrBiscuit** [DataDog/datadog-serverless-functions#177]
I see there's the `DD_FETCH_LAMBDA_TAGS` env var that has the capability to add the service tags to the `aws.lambda.enhanced.*` metrics but I don't see the ability to do this for log tagging yet.  We'd love to be able to pull the tags from our AWS services sending logs to Datadog and have those tags show up on the logs as searchable fields.  For instance we use the `Service:<service_name>` tag on many of our lambdas.  It'd be great if that tag was applied to the logs from those lambdas, along with any other tags on the lambdas.

![](https://p-BOFBBg.b4.n0.cdn.getcloudapp.com/items/YEuvYevG/Image+2019-11-14+at+2.10.47+PM.png?v=8e8d87eb4bab99dc8252e08ad209343e)

![](https://p-BOFBBg.b4.n0.cdn.getcloudapp.com/items/lluwb72Z/Image+2019-11-14+at+2.13.14+PM.png?v=befeec0165991c37a2a4b5f0fab326fe)

**Comment by tianchu** [comment]
@PurrBiscuit `DD_FETCH_LAMBDA_TAGS` now applies lambda tags to logs (and custom metrics) too. [Upgrade](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#updating) to the latest version :)
