### ISSUE TITLE
DataDog Forwarder template doesn't allow adding additional log groups 

### ISSUE THREAD

**Issue by Dunedan** [DataDog/datadog-serverless-functions#207]
The documentation for the log forwarder describes how to manually add additional (non-Lambda) CloudWatch Log groups as triggers to its Lambda function (https://docs.datadoghq.com/integrations/amazon_web_services/?tab=allpermissions#collecting-logs-from-cloudwatch-log-group). However that feature doesn't seem to be supported by the SAM template yet. It'd be great if there would be support for that to avoid having manually edit the configuration of the AWS Lambda function of the DataDog Forwarder.

**Comment by rromanchuk** [comment]
@Dunedan  does this mean any manual triggers added to the lambda function (i guess i'm answering my own question) get wiped out if i need to upgrade or update cloudformation template settings?

I havent looked at this cloudformation template/custom resource to check if it's destructive, just trying to save some time before i manually start wiring up s3/cloudwatch logs

**Comment by tianchu** [comment]
Thanks @Dunedan, we have a ticket internally to allow user specify log sources (s3 buckets or log groups) as part of the forwarder configuration. We also updated that doc you referenced with examples how to configure the log subscription as part of your Lambda function's (who generates the logs) configuration if your function is managed/deployed using Terraform, serverless framework, SAM, or CloudFormation.

**Comment by tianchu** [comment]
@rromanchuk i think you might have already figured this out, but per to my previous comment, the forwarder template does not manage triggers (s3 event notification or cloudwatch log subscriptions) at all, so installing the stack won't impact your existing triggers.
