### ISSUE TITLE
template.yaml fails cfn-lint check

### ISSUE THREAD

**Issue by flagscript** [DataDog/datadog-serverless-functions#230]
**Describe what happened:**
It's common to deploy templates in a ci/cd pipeline, where templates are linted by cfn-lint. 

**Describe what you expected:**
template.yaml to pass cfn-lint checks. Currently - the template.yaml yields the following cfn-lint warning and error:

[cfn-lint] W2510: Lambda Memory Size parameters should use MinValue, MaxValue or AllowedValues at Parameters/MemorySize
template.yaml:22:3

[cfn-lint] E3012: Property Resources/Forwarder/Properties/Environment/Variables/DD_ENHANCED_METRICS should be of type String
template.yaml:269:11

**Steps to reproduce the issue:**
Run
* cfn-lint --template template.yaml

**Suggested Resolution:**
* Add Max/Min value to parameter for current lambda boundaries, so the template passes link checks without errors/warnings. 
* Change DD_ENHANCED_METRICS to string

**Comment by tianchu** [comment]
Thanks @flagscript, I will help fix these and set up a cfn-lint check against future PRs.

**Comment by flagscript** [comment]
@tianchu Thanks! I didn't add the cfn-lint to release.sh, but did just put in a mini-pull to fix the linting for now if interested.

**Comment by tianchu** [comment]
Thanks for your PR! Since you already have the PR, do you mind adding this check https://github.com/marketplace/actions/cfn-lint-action to https://github.com/DataDog/datadog-serverless-functions/tree/master/.github/workflows?

You probably need `on: [push, pull_request]` to enable the check to run against PRs from forked repo.

**Comment by flagscript** [comment]
For sure! I'll take a look at this tomorrow! Thanks!
