### ISSUE TITLE
Expose API Key secret ARN in template outputs

### ISSUE THREAD

**Issue by abustany** [DataDog/datadog-serverless-functions#235]
Version: 3.5.0

When setting a permission boundary for the lambda (for example because I don't want the lambda to be able to do a `GetObject` on all my S3 buckets), it'd be useful to be able to access the ARN of the DD API Key secret (so that I can refer to it eg. in Terraform templates). Otherwise, I need to allow the lambda to access all secrets in the boundary... Or am I doing something wrong?

**Comment by tianchu** [comment]
I'm not sure if I understand your question correctly, but the Forwarder's execution role is only allowed to access the `DdApiKey` secret: https://github.com/DataDog/datadog-serverless-functions/blob/bb8a82e6ba8b7984ee1b399e6ebbd5c7373ee71c/aws/logs_monitoring/template.yaml#L382. If this doesn't answer your question, can you provide more context?

**Comment by abustany** [comment]
yes, the current code is correct. I guess the whole point of the boundary is to make sure that even if there's a bug/an attack in the future and I update the log forwarder to that buggy/hacked version the boundary will ensure that nothing can go wrong: even if the CF template would be changed to allow access to all secrets, *I* am in control of the boundary so the lambda can still only access one secret.

for now I worked it around by using name prefixes in the boundary, which is close enough to what I need :)

**Comment by tianchu** [comment]
Ah, I see. I'm going to close the issue for now, but feel free to reopen or submit a PR to get what you need :)
