### ISSUE TITLE
Support json log attributes aws_request_id

### ISSUE THREAD

**Issue by alejandrod** [DataDog/datadog-serverless-functions#247]
**Describe what happened:**
When json logs are used, the `lambda.request_id` is not set. This is needed to track specific runs.

The default lambda `LambdaLoggerHandler` is adding `aws_request_id`
This is a json Example
```json
{
    "asctime": "2020-04-12 13:02:48,759",
    "levelname": "INFO",
    "name": "root",
    "message": "Some log",
    "aws_request_id": "e6314594-xx-4b43-afee-xxxxx"
}
```

**Describe what you expected:**
I'd expect `aws_request_id` to be set at `lambda.request_id` instead of at `aws_request_id`
The result is that the value is not tracked properly

**Steps to reproduce the issue:**
Just log that line and see the result.

**Comment by tianchu** [comment]
Hi @alejandrod the forwarder lambda is only responsible for forwarding the logs, is this issue for our Lambda layer? e.g., this is the repo for the Python layer https://github.com/DataDog/datadog-lambda-layer-python. 

To help us reproduce the issue, do you mind sharing the following info with us?

- The Lambda runtime
- The Datadog Lambda layer version (if used)
- The library used for json logging
- The minimal function code that reproduces the issue

Thanks!
