### ISSUE TITLE
Not working in cn-northwest-1

### ISSUE THREAD

**Issue by jaidevs21** [DataDog/datadog-serverless-functions#248]
**Describe what happened:**
Getting below Error:-
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': from __future__ imports must occur at the beginning of the file (lambda_function.py, line 6)
Traceback (most recent call last):
  File "/var/task/lambda_function.py" Line 6
    from __future__ import print_function

**Describe what you expected:**
It should transfer logs to my datadog account.

**Steps to reproduce the issue:**
create a lambda function in cn-northwest-1 region using only lambda_function.py file without adding datadog layers, setup manual triggers for log group.

**Comment by tianchu** [comment]
Hi @jaidevs21 as you can see in [lambda_function.py](https://github.com/DataDog/datadog-serverless-functions/blob/71eabbff4182643134d3717a6584246270aec407/aws/logs_monitoring/lambda_function.py#L6) `from future import print_function` is indeed at the beginning of the file. Do you mind double checking the actual `lambda_function.py` file content in Lambda code editor? Perhaps some extra content got it during the copy/paste? If not, can you try deleting all the comment lines before the `from future import print_function` line and try again (i don't think that would be a difference, but who knows)?

BTW, we have the [manually installation steps](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#manual-installation) documented, which uses the zip from the github [releases](https://github.com/DataDog/datadog-serverless-functions/releases), which would help avoid an error-prone copy/paste.

**Comment by jaidevs21** [comment]
Thanks Tianchu, it was working fine in Ireland or in frankfurt, the only difference between china and global regions is that I did not used Datadog layers in china as they were not available for that region.

I will also try what you have suggested, but can you please let me know whether it will work without layers or not.

**Comment by jaidevs21** [comment]
You were correct there was a type error, after correcting that I am getting below error
[ERROR]	2020-04-14T06:22:13.933Z		Could not import the 'requests' package, please ensure the Datadog Lambda Layer is installed. https://dtdg.co/forwarder-layer

[DEBUG]	2020-04-14T08:53:54.914Z		Could not import from the Datadog Lambda layer, metrics can't be forwarded


Can you please suggest, and why cant I set automatic triggers for this?

**Comment by tianchu** [comment]
@jaidevs21 the forwarder has two jobs -- 1. forward logs and 2. forward custom metrics for Lambda functions (submitted via logs). Those errors are expected when layers are not attached, and the forwarder won't be able to forward custom metrics for Lambda functions, but it can still forward logs without problems.

Do you have any issue with automatic trigger configuration?

**Comment by jaidevs21** [comment]
Manual triggers are working fine but getting errors while setting Automatic triggers

ARN is arn:aws-cn:lambda:cn-northwest-1:***********:function:cw1-p1-datadog-forwarder

and while putting the ARN in INTEGRTIONS -> AWS -> Collect logs, getting below error.
**That Lambda ARN is not valid, please check it and try again**

and if I add the ARN by removing "-cn" like this 
"ARN is arn:aws:lambda:cn-northwest-1:***********:function:cw1-p1-datadog-forwarder"

 I get below error :-
**There was an error encountered while trying to set up triggers for this Lambda. The problem may be that you need to remove triggers that you have manually added to this Lambda before we can automatically manage them.**

but there are no manual triggers.

**Comment by tianchu** [comment]
@jaidevs21 I just did some test and confirmed that's a bug with the validation logic not recognizing `arn:aws-cn:*` ARN. However, if you set up triggers manually, the forwarder "_should_" work. Can you try [enable debugging logs](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#troubleshooting) for the forwarder and see if that helps reveal any issue? 

If you have access to Slack, I'd love to help you out at our community slack channel https://datadoghq.slack.com/channels/serverless/.

**Comment by jaidevs21** [comment]
Thanks Tianchu, it is working fine with Manual triggers, but I need to fetch logs from all log-group and it is not possible for me to set up manual trigger for all of them.

Can you please suggest some other way to do this.

**Comment by tianchu** [comment]
@jaidevs21 we have prioritized the bug fix, however, we would need your help to test it, since we don't yet have an account in AWS China. That's why I was asking whether you can join https://datadoghq.slack.com/channels/serverless/.

A temporary workaround I can think of is writing a simple script like this (just the idea):

```bash
# allow the forwarder to be invoked by any cloudwatch log group
aws lambda add-permission \
    --function-name "<forwardername>" \
    --statement-id "allow-logs-invoke-dd-forwarder" \
    --principal "logs.region.amazonaws.com" \
    --action "lambda:InvokeFunction" 
# find all the lambda log groups
aws logs describe-log-groups --log-group-name-prefix "/aws/lambda/" 
# loop through the log groups and add the subscription filter
aws logs put-subscription-filter \
    --log-group-name <loggroupname> \
    --filter-name "dd-forwarder" \
    --filter-pattern "" \
    --destination-arn <forwarderarn>
```

You could alternatively write this in Python using `boto3` and run it in a lambda periodically to automatically subscribe the forwarder to new log groups.

Again, we are working on the fix, just suggesting a workaround if you would like to get things set up immediately.

**Comment by jaidevs21** [comment]
sure, will join that channel.

Thanks for your timely response.
