### ISSUE TITLE
AWS Account ID missing from forwarded CloudWatch Events

### ISSUE THREAD

**Issue by nickdgriffin** [DataDog/datadog-serverless-functions#255]
**Describe what happened:**
We are shipping GuardDuty findings to Datadog (as per https://docs.datadoghq.com/integrations/amazon_guardduty/) and have noticed that the log messages do not appear with the `account_id` field unlike the CloudWatch logs we are shipping from Lambda log groups. We are using verison `3.3.0` across all of our exporters.

**Describe what you expected:**
I expect the AWS account ID tag to be present on all logs that are shipped so that we can tell where a message came from, without having to apply a custom tag ourselves.

**Steps to reproduce the issue:**
Setup GuardDuty with a CloudWatch rule to send finding events to the Datadog log forwarder Lambda, and observe the tags on the messages when they are received.

**Comment by nickdgriffin** [comment]
Looks like it happens because this method returns if the event isn't from Lambda: https://github.com/DataDog/datadog-serverless-functions/blob/65f6950031170e02f1f5b76886a5e36242e04025/aws/logs_monitoring/lambda_function.py#L634-L665

This would call: https://github.com/DataDog/datadog-serverless-functions/blob/65f6950031170e02f1f5b76886a5e36242e04025/aws/logs_monitoring/enhanced_lambda_metrics.py#L424

Which then calls the function that enriches: https://github.com/DataDog/datadog-serverless-functions/blob/65f6950031170e02f1f5b76886a5e36242e04025/aws/logs_monitoring/enhanced_lambda_metrics.py#L344-L364

Meaning any other event source isn't enriched with the additional account ID tag, which would be useful to have as we have multiple forwarders deployed across multiple accounts and we don't want to have to rely on the uniqueness of the name to tell them apart.

We could add a custom tag I guess, but for the account ID this feels like something the forwarder should do.

**Comment by tianchu** [comment]
Hi @nickdgriffin looks like we didn't get enough demand/request for this feature, so I'm closing the issue.  But if you would like to submit PR in the future, we are more than happy to review it.
