### ISSUE TITLE
Resource tagging API calls causing many CloudTrail errrors, permission denied

### ISSUE THREAD

**Issue by martinb3** [DataDog/datadog-serverless-functions#263]
**Describe what happened:**

I'm seeing permission denied errors across many, many services from the log forwarding Lambda in this repo, when deployed into AWS. Some examples:

SNS, ListTagsForResource
S3, GetBucketTagging
RDS, ListTagsForResource

I don't have enhanced metrics enabled by default, so I can't work out why the log forwarding Lambda is doing this, but I see that the CloudFormation YAML template doesn't ship with permissions for these calls.

Note, from the resource tagging API docs:

> You'll also need permissions to access the resources of individual services so that you can tag and untag those resources.
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/Welcome.html

Perhaps it should ship with those permissions for various services?

**Describe what you expected:**

I didn't expect the log forwarding Lambda to make these calls at all.

**Steps to reproduce the issue:**

Deploy this template into an AWS account, subscribe the resulting Lambda to CloudTrail events and Lambda logs.

**Comment by tianchu** [comment]
@martinb3 

>You'll also need permissions to access the resources of individual services so that you can tag and untag those resources.

I don't think this is needed to query the tags. It's needed to tag or untag.

If you have [DdFetchLambdaTags ](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L55) set to `true`, the execution role will be granted with the permission [tag:GetResources](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L425). However, the forwarder is only supposed to query for [Lambda tags](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/enhanced_lambda_metrics.py#L293).

Which IAM role made those API calls? Do you mind sharing one of the sample event from CloudTrail?

**Comment by martinb3** [comment]
Hi there -- I see what's happening here. I'm actually seeing CloudTrail logs shipped by the forwarder, and there's tags for both the Lambda doing the forwarding, as well as the actual event (which is from another caller). Please disregard! :)
