### ISSUE TITLE
Feature Request: Parameterize S3 permissions in log forwarder template

### ISSUE THREAD

**Issue by SpokMike** [DataDog/datadog-serverless-functions#268]
The current aws log forwarding template grants a "GetObject" permission [on any S3 bucket](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L415). I recognize that this is to allow the forwarder lambda to pick up logs from services that send to S3. However for those of us who don't capture logs this way, the permission seems overly broad.

Would it be possible to parameterize and condition that permission so that it could be turned off if not needed?

Thank you.

**Comment by tianchu** [comment]
Hi @SpokMike you can deny that permission by setting a permission boundary https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L159

**Comment by SpokMike** [comment]
Sure. We currently have a customized version of this template and I'll admit that I was hoping to transition to using the vendored template straight out of the box, and to limit additional resources/policies we'd need to build.

But fair enough if this isn't a broad enough need to modify the template.

**Comment by tianchu** [comment]
Yeah, I do recommend using the template provided by us with a permission boundary to tailor the scope of permissions. It's quite common to find customers with similar needs, but every case is unique, we don't want to inflate the template with a parameter for each.

But I'll leave this issue open for a while and see if we find enough customers with the same need.

**Comment by SpokMike** [comment]
Thanks @tianchu . I appreciate it.

**Comment by bryantbiggs** [comment]
just FYI - with the ability to better parameterize in terraform we have been able to improve the security posture of the policies generated in the terraform module of the forwarders as shown here https://github.com/clowdhaus/terraform-aws-datadog-forwarders/blob/a8cfc2e847fbf7fbbf19fd90116260f3d5318743/modules/log_forwarder/policy.tmpl#L32 - we only apply the `getObject` permission for S3 buckets that are provided where users want to forward logs from s3 buckets they chose (via the user specifying the S3 ARNs they want to forward logs from and therefore only these buckets are allowed `getObject`) while still allowing for a more broader access on the log forwarder bucket where the zip archive and tag cache object are stored

Ref: https://github.com/clowdhaus/terraform-aws-datadog-forwarders

**Comment by agocs** [comment]
SLS-1324

**Comment by dgoade55** [comment]
The permissions seem overly broad in another, more significant way. The ForwarderRolePolicy0 policy sets s3:* wildcard actions as can be seen [here](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml#L625) despite the fact that according to your documentation at [permissions](https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#permissions) stating that only s3:GetObject is necessary.

**Comment by dgoade55** [comment]
> The permissions seem overly broad in another, more significant way. The ForwarderRolePolicy0 policy sets s3:* wildcard actions as can be seen [here](https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/template.yaml?rgh-link-date=2021-07-30T11%3A29%3A52Z#L625) despite the fact that according to your documentation at [permissions](https://docs.datadoghq.com/serverless/libraries_integrations/forwarder/#permissions) stating that only s3:GetObject is necessary.

I have simply removed this block from the policy and the lambda is continuing to ship our alb logs to dd fine without it:
```
        {
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::datadog-forwarder-alb-prod-forwarderbucket-[redacted]/*"
            ],
            "Effect": "Allow"
        },
```

**Comment by tianchu** [comment]
@dgoade55 that `s3:*` permission is only asked for one specific bucket, namely the forwarder bucket, which is created to host a file as a cache for Lambda tags. The forwarder periodically fetches the latest resources tags for Lambda functions, caches them in that file, so they can be applied to Lambda logs going through the forwarder. If you don't send Lambda function logs, or don't need to apply Lambda tags onto their logs, removing that policy is fine.

**Comment by dgoade55** [comment]
thank you. I'll double check that that. however, does it really need s3:* for that?

**Comment by dgoade55** [comment]
> thank you. I'll double check that that. however, does it really need s3:* for that?

I ask because our security scanner flags any role with wildcard actions as high risk and with rare exceptions, I agree.

**Comment by bryantbiggs** [comment]
@dgoade55 you only need these for the forwarder to use https://github.com/clowdhaus/terraform-aws-datadog-forwarders/blob/a8cfc2e847fbf7fbbf19fd90116260f3d5318743/modules/log_forwarder/policy.tmpl#L18-L27

**Comment by dgoade55** [comment]
> @dgoade55 you only need these for the forwarder to use [clowdhaus/terraform-aws-datadog-forwarders@`a8cfc2e`/modules/log_forwarder/policy.tmpl#L18-L27](https://github.com/clowdhaus/terraform-aws-datadog-forwarders/blob/a8cfc2e847fbf7fbbf19fd90116260f3d5318743/modules/log_forwarder/policy.tmpl#L18-L27)

Awesome! Thank you very much for helping me pare these actions down to something more reasonable.

**Comment by tianchu** [comment]
I think that's definitely reasonable to update the policy's action to a more limited scope. I can help make that change.

**Comment by tianchu** [comment]
Closing because https://github.com/DataDog/datadog-serverless-functions/pull/486 has been merged. Will be soon released in the next version.
