### ISSUE TITLE
Feature Request: Apply Cloudwatch Log Group Tags as Datadog Tags

### ISSUE THREAD

**Issue by kellydunn** [DataDog/datadog-serverless-functions#269]
Hello there!

We love the capabilities of the Data Logging Pipeline, and we use it quite heavily today!  One feature we've always enjoyed is the nice UX of installing an agent and having it aggregate EC2 Tagging metadata as tags in Datadog's Logging product.

We also make heavy use of the Datadog Log Forwader for our ECS Workloads, however, we've noticed that some of the metadata we used to get in EC2 isn't necessarily working how we'd expect with Cloudwatch log groups.

What would be really nice is if this same behavior applied to Cloudwatch Log Groups so we wouldn't have to encode aggregation data into our Structured Logs and try to parse it out via the Logging Pipeline.

For example, if we tag a Cloudwatch log group resource in AWS with

```
Env: 'production'
Service: 'auth'
```

We would love to have any logs from that log group be searchable and aggregated by those tags as well!

**Comment by eboulfakhr** [comment]
Hello!
We have a similar need. I added tags to the aws elasticsearch slow logs logroup but I am not able to see these tags in the the logs forwarded to datadog.

thank you!

**Comment by dominics** [comment]
As an additional use case: this is the only way we'd be able to tag AWS Glue logs with unified tagging.

That's because there's no Lambda for the Forwarder to look up the tags of, and the log events themselves are formatted by the service. [Datadog's Glue docs](https://docs.datadoghq.com/integrations/amazon_glue/#send-logs-to-datadog) recommend using the Forwarder, but don't mention you can't use it with tagging.

**Comment by agocs** [comment]
SLS-1325

**Comment by HartmannVolker** [comment]
Would love to see that 👍  we are forwarding API Gateway access logs to datadog using the lambda forwarder. Without the service and env tag it is hard to correlated these logs with the lambda invocations.

**Comment by podon** [comment]
Bump. Any traction on this request?

**Comment by tianchu** [comment]
Closing. because it's done by https://github.com/DataDog/datadog-serverless-functions/pull/540
