### ISSUE TITLE
Forwarder not sending traces to datadog

### ISSUE THREAD

**Issue by alaingoga** [DataDog/datadog-serverless-functions#283]
**Describe what happened:**
I have a lambda function that use serverless plugin https://github.com/DataDog/serverless-plugin-datadog (_that attaches the Datadog Lambda Layers for Node.js to your functions. At deploy time, it generates new handler functions that wrap your existing functions and initializes the Lambda Layers. It also enables X-Ray tracing for your Lambda functions and API Gateways._) on cloudwatch I can see the logs, enhanced metrics and traces. 

![image](https://user-images.githubusercontent.com/658031/84540326-11798c00-acc3-11ea-8859-90e870d45e0f.png)

The forwarder lambda is able to send logs and enhanced metrics to data dog but traces are not showing anywhere.

**Describe what you expected:**
I expect to see the lambda traces on the serverless infrastructure panel (https://app.datadoghq.com/functions)  and also in APM

**Steps to reproduce the issue:**
I created this repo with the code I'm using to isolate the problem: https://github.com/alaingoga/lambda-datadog-integration
Forwarder should be installed on AWS and then this project has to installed and lambda deployed using serverless.

I wonder is there is a flag or configuration we are missing in the forwarder integration that is preventing traces to be picked up.

**Comment by agocs** [comment]
Hey Alain, would you mind contacting support about this? They can look up specifics about your account that I can't from a Github issue. https://docs.datadoghq.com/help/

**Comment by alaingoga** [comment]
Yeah, I did and they are looking into that, but I was not sure, if the problem was on the forwarder side if they would have enough visibility. Thanks for fast reply, I'll follow up with them.

**Comment by agocs** [comment]
Awesome. Thanks. Yeah, if it winds up being a bug in the forwarder the ticket will get escalated to my team with all the relevant information attached.

**Comment by pyaesone17** [comment]
@agocs Hi I am facing the same issue. 
@alaingoga Did u get any solution for that particular problems ?

**Comment by agocs** [comment]
Hey @pyaesone17, make sure you have the [Datadog AWS Forwarder](https://docs.datadoghq.com/serverless/forwarder/) installed, and that your lambda function's log group has a subscription on it that points to that forwarder. Once you've done that, email support@datadoghq.com -- they'll be able to peek inside your account and get all the relevant information!

**Comment by pyaesone17** [comment]
> Hey @pyaesone17, make sure you have the [Datadog AWS Forwarder](https://docs.datadoghq.com/serverless/forwarder/) installed, and that your lambda function's log group has a subscription on it that points to that forwarder. Once you've done that, email [support@datadoghq.com](mailto:support@datadoghq.com) -- they'll be able to peek inside your account and get all the relevant information!

Thanks for the reply, actually forwarder is already installed, and it is working pretty well with data dog log management. The only problem is with metrics and traces not showing up in dashboard.
