### ISSUE TITLE
Feature Request: Use SSM SecureString instead of SecretsManager

### ISSUE THREAD

**Issue by davidcomerford** [DataDog/datadog-serverless-functions#285]
Hi there,

The Datadog API key is stored in SecretsManager which costs $0.40/month.
If there is no plans to ever use any features of SecretsManager then moving the API key to a SecureString in SSM Parameter Store would be free.

**Comment by rnegron** [comment]
@davidcomerford After inspecting the source code, it seems like there is support for storing the API key in SSM! See the code here: https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/settings.py#L182

So all that's required is setting the `DD_API_KEY_SSM_NAME` environment variable in the Lambda configuration with the full SSM parameter name and granting the Lambda execution IAM role the `ssm:GetParameter` permission, ideally on the specific SSM key via ARN. See: https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameter.html

I can confirm that this works!

Caveat: This is for the log monitor in specific, which is what I tested.

**Comment by bryantbiggs** [comment]
just note that at high usage, you will get throttled on SSM `getParameter` requests
