### ISSUE TITLE
Null value in one metric causes metric flush fail for all metrics.

### ISSUE THREAD

**Issue by ktersius** [DataDog/datadog-serverless-functions#295]
**Code versions.**
dd_forwarder_version | 3.14.0
datadog-lambda-js | 2.24.0

If for some other reason you log a non number value in the sendDistributionMetric, in my case it was NaN, it will cause all metrics to fail being parsed by the DD log forwarder.

**Describe what you expected:**

In the DD Log Forwarder: 

The null value metric should be ignored and a proper error for that specific metric value should be logged instead of failing with:
```
File "/var/task/datadog/threadstats/reporters.py", line 21, in flush_distributions
2020-07-08T10:34:15.596+12:00
api.Distribution.send(distributions, compress_payload=self.compress_payload)
2020-07-08T10:34:15.596+12:00
File "/var/task/datadog/api/distributions.py", line 33, in send
2020-07-08T10:34:15.596+12:00
d['points'] = format_points(d['points'])
2020-07-08T10:34:15.596+12:00
File "/var/task/datadog/api/format.py", line 33, in format_points
2020-07-08T10:34:15.596+12:00
value = [float(p) for p in point[1]]
2020-07-08T10:34:15.596+12:00
File "/var/task/datadog/api/format.py", line 33, in <listcomp>
2020-07-08T10:34:15.596+12:00
value = [float(p) for p in point[1]]
2020-07-08T10:34:15.596+12:00
TypeError: float() argument must be a string or a number, not 'NoneType'
```

In the datadog-lambda-js npm package:

- It it should either throw some Error. "Invalid metric value" etc....
- Not log the metric at all and possibly log an error. 

**Steps to reproduce the issue:**

1. Send a NaN value into the sendDistributionMetric and other valid metric values.
2. Observe the logged out value in cloudwatch like below.
3. View the errors thrown by python DD Log Forwarder lambda function as above.

Offending Cloudwatch entry that breaks DD Forwarder.
```
{"e":1594158306.777,"m":"nodemaster.max.indicatorLastResponseSeconds","t":["environment:PRODUCTION","dd_lambda_layer:datadog-nodev12.16.3"],"v":null}
```

**Client usage fix.**
I ended up ensuring that only numbers get sent as metrics to sendDistributionMetric

```
export function isNumber(n): boolean {
  return !isNaN(parseFloat(n)) && isFinite(n);
}

if (isNumber(value)) {
    sendDistributionMetric(metricName, value, ...tags);
}
```

**Comment by tianchu** [comment]
@ktersius somehow we missed your report, but we have fixed it https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.18.2
