### ISSUE TITLE
How do datadog subscribe to Cloudwatch Logs? Can we limit the Cloudwatch Subscription specific to log groups? 

### ISSUE THREAD

**Issue by bala1074** [DataDog/datadog-serverless-functions#322]
I tried out datadog serverless setup, I see datadog is subscribing to all the cloudwatch log groups. How to limit the subscription to limited log groups. And also how the subscription was happening.

**Comment by DarcyRaynerDD** [comment]
Hi @bala1074, when you configure automatic log forwarding subscriptions, our backend will periodically crawl your account for any lambda log groups and subscribe them to the forwarder. If you don't want this, you can disable automatic log forwarding subscriptions, and use another method to subscribe the log group, such as by using our datadog-ci tool, serverless framework plugin or SAM macro https://docs.datadoghq.com/serverless/installation/nodejs/?tab=serverlessframework.

**Comment by DarcyRaynerDD** [comment]
@bala1074 This is a better link that describes the process of setting up manual triggers https://docs.datadoghq.com/logs/guide/send-aws-services-logs-with-the-datadog-lambda-function/?tab=cloudformation#manually-set-up-triggers

**Comment by bala1074** [comment]
@DarcyRaynerDD thank you

**Comment by tianchu** [comment]
@bala1074 I'm going to close this issue, if you still need help, feel free to submit a feature request at support@datadoghq.com.
