### ISSUE TITLE
Cloudformation template for forwarder cannot be created in cn-north-1

### ISSUE THREAD

**Issue by stroem** [DataDog/datadog-serverless-functions#346]
**Describe what happened**
Trying to create a datadog forwarder on China cn-north-1 by using the template with version 3.18.0.
Getting this error:
```
The provided principal was invalid. Please check the principal and try again.
(Service: AWSLambda; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: bd862980-3bd2-4acc-9f63-2fc9ec2aa1d8; Proxy: null)
```
on resource with logical id `S3Permission` in the CloudFormation template

**Describe what you expected**
Should be able to create the stack without errors

**Steps to reproduce the issue**
Create a new stack with the CloudFormation template, version 3.18.0 in China region cn-north-1
Link to template: https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.18.0.yaml

**Comment by tianchu** [comment]
@stroem thanks for the bug report, unfortunately we don't have any account in AWS China for testing, do you already have a fix in mind? If so, would you mind submitting a pull request?

**Comment by stroem** [comment]
@tianchu thanks for the fast response.

I believe not all principals has the *.cn suffix on cn-north-1.
Based on that I tried to create the stack by changing the `S3Permission` princpal to be "s3.amazonaws.com" and it seems to be working, the stack is created successfully.

Haven't yet looked at what `S3Permission` is used for, is it used for uploading the lambda zip to? If that is the case this solution is looking good.

**Comment by stroem** [comment]
Update: it is working. Will submit a PR shortly

**Comment by tianchu** [comment]
`S3Permission` allows the forwarder to fetch log from S3 (S3 only notify the forwarder there is a new file, and the forwarder needs to fetch it). Again, thanks for your fix! Let me know if you need additional help :)

**Comment by stroem** [comment]
No problems 👍 

FYI: cn-northwest-1 has different issue when deploying the cloudformation template, thats another issue. It didn't work before the PR fix either.

**Comment by stroem** [comment]
@tianchu when is a next release planned?

**Comment by tianchu** [comment]
@stroem `3.18.1` just got released.
