### ISSUE TITLE
Datadog-RDS-Enhanced function is broken

### ISSUE THREAD

**Issue by bitphage** [DataDog/datadog-serverless-functions#348]
**Describe what happened:**

I tried to enable AWS RDS enhanced monitoring as described in https://docs.datadoghq.com/integrations/amazon_rds/?tab=enhanced#create-your-lambda-function and it's not working. In the events an error is logged

```
module initialization error
An error occurred (InvalidCiphertextException) when calling the Decrypt operation:
```

Probably this could be fixed with https://github.com/DataDog/datadog-serverless-functions/pull/293

**Comment by agocs** [comment]
Fixed in #309
