### ISSUE TITLE
Lambda executions failing with "Required parameter bucket_name not set"

### ISSUE THREAD

**Issue by taiidani** [DataDog/datadog-serverless-functions#361]
**Describe what happened:**

After updating to the newest Lambda version, our Datadog Lambdas began emitting errors at a rapid clip. This appears to have been related to an S3 bucket dependency having been added in https://github.com/DataDog/datadog-serverless-functions/pull/343 with a default env var value of "None" but the code not handling it not being present. It looks like this changed from in-memory caching to S3 caching right before release?

![image](https://user-images.githubusercontent.com/902500/94494897-2829ed00-01a5-11eb-8d27-2e4f3d1008cd.png)

```
[ERROR] ValueError: Required parameter bucket_name not set
Traceback (most recent call last):
  File "/var/task/datadog_lambda/wrapper.py", line 106, in __call__
    return self.func(event, context, **kwargs)
  File "/var/task/lambda_function.py", line 414, in datadog_forwarder
    metrics, logs, trace_payloads = split(enrich(parse(event, context)))
  File "/var/task/lambda_function.py", line 514, in enrich
    add_metadata_to_lambda_log(event)
  File "/var/task/lambda_function.py", line 586, in add_metadata_to_lambda_log
    custom_lambda_tags = get_enriched_lambda_log_tags(event)
  File "/var/task/enhanced_lambda_metrics.py", line 657, in get_enriched_lambda_log_tags
    lambda_custom_tags = account_lambda_tags_cache.get(log_function_arn)
  File "/var/task/enhanced_lambda_metrics.py", line 175, in get
    self._refresh()
  File "/var/task/enhanced_lambda_metrics.py", line 130, in _refresh
    tags_fetched, last_modified = get_cache_from_s3()
  File "/var/task/enhanced_lambda_metrics.py", line 401, in get_cache_from_s3
    cache_object = s3_client.Object(DD_S3_BUCKET_NAME, DD_S3_CACHE_FILENAME)
  File "/var/runtime/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/var/runtime/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
```

Note that logs are still flowing and Datadog has begun collecting some enhanced metrics from our functions, but the Datadog UI does not reflect "Enhanced Metrics" as being enabled. I assume that the process fails partially through and doesn't complete the full upload.

**Describe what you expected:**

Existing behavior would be retained, with additional enhanced metrics due to the way we follow the "manual" installation steps (see below) and no errors being emitted from the functions.

**Steps to reproduce the issue:**

We follow [the "manual" installation steps](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#manual), which do not make any mention of an S3 bucket requirement.

```terraform
data external logger {
  # Locked to releases from: https://github.com/DataDog/datadog-serverless-functions/releases
  # Change the URL and rerun to update to newer versions.
  program     = ["/bin/sh", "lambda.sh", "https://github.com/DataDog/datadog-serverless-functions/releases/download/aws-dd-forwarder-3.20.0/aws-dd-forwarder-3.20.0.zip"]
  working_dir = path.module
}

resource aws_lambda_function logger {
  depends_on       = [aws_cloudwatch_log_group.logger, data.external.logger]
  function_name    = "logger-datadog"
  description      = "Created by the Root account. Ships logs to Datadog Logs"
  handler          = "lambda_function.lambda_handler"
  role             = aws_iam_role.logger.arn
  runtime          = "python3.7"
  filename         = "${path.module}/${data.external.logger.result.filename}"
  source_code_hash = filebase64sha256("${path.module}/${data.external.logger.result.filename}")
  memory_size      = 512
  timeout          = 120
  tags             = var.common_tags

  layers = [
    "arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Python37:21",
    "arn:aws:lambda:us-west-2:464622532012:layer:Datadog-Trace-Forwarder-Python37:5",
  ]

  environment {
    variables = {
      DD_API_KEY_SECRET_ARN = aws_secretsmanager_secret.api_key.arn
      DD_TAGS               = "${var.team == "" ? "" : "team:${var.team},project:${var.project},"}product:${var.project},env:${var.env},environment:${var.environment}"
      DD_FETCH_LAMBDA_TAGS  = "true"
      DD_ENHANCED_METRICS   = "false"
    }
  }
}

resource aws_iam_role logger {
  name = "lambda-logger-datadog-role"
  tags = var.common_tags

  assume_role_policy = <<EOF
{
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": "sts:AssumeRole",
          "Principal": {
            "Service": "lambda.amazonaws.com"
          },
          "Effect": "Allow"
        }
      ]
    }
EOF
}

data aws_iam_policy_document logger_policy {
  statement {
    sid       = "LambdaDatadogApiKey"
    actions   = ["secretsmanager:GetSecretValue"]
    resources = [aws_secretsmanager_secret.api_key.arn]
  }

  statement {
    sid       = "LambdaCollectTags"
    actions   = ["tag:GetResources"]
    resources = ["*"]
  }
}

resource aws_iam_role_policy logger_policy {
  role   = aws_iam_role.logger.name
  policy = data.aws_iam_policy_document.logger_policy.json
}

resource aws_iam_role_policy_attachment logger_datadog {
  role       = aws_iam_role.logger.name
  policy_arn = aws_iam_policy.datadog.arn
}

resource aws_iam_role_policy_attachment logger_basic_execution {
  role       = aws_iam_role.logger.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

resource aws_iam_role_policy_attachment logger_s3_read {
  role       = aws_iam_role.logger.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
}
```

**Comment by hghotra** [comment]
Hi @taiidani , thanks for catching this - I've gone ahead and updated the docs in [this PR](https://github.com/DataDog/datadog-serverless-functions/pull/362). Give the updated instructions a shot and let me know if you're still seeing any issues.

**Comment by taiidani** [comment]
@hghotra Currently testing this with the following bucket configuration. Will the rules I set work well with the Datadog logic?

```terraform
resource aws_s3_bucket logger {
  bucket = "logger-datadog-${data.aws_caller_identity.current.account_id}"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }

  versioning {
    enabled = true
  }

  lifecycle_rule {
    id      = "retention"
    enabled = true

    transition {
      days          = 90
      storage_class = "GLACIER"
    }

    expiration {
      days                         = 180
      expired_object_delete_marker = false
    }

    noncurrent_version_expiration {
      days = 7
    }
  }

  tags = merge(var.common_tags, {
    Name = "logger-datadog-${data.aws_caller_identity.current.account_id}"
  })
}

```

**Comment by taiidani** [comment]
@hghotra I'm definitely seeing the Lambda error rate go down for the Datadog function, and I'm not seeing the stack traces in the logs anymore. It looks like adding the bucket env var worked!

Incidentally I was hoping that fixing these errors would flip the "Enhanced Metrics" bit on the Infrastructure => Serverless view in the UI, but it's not flipping for any of my company's functions even though teams have completed the other setup steps in their function configurations.

![image](https://user-images.githubusercontent.com/902500/94951707-a2a28780-0499-11eb-92e5-f11e270d8ff4.png)

Do you know if that's related? If not, I can file a support ticket instead.

**Comment by bryantbiggs** [comment]
@taiidani FYI we have created a terraform module for the forwarders if that interests you https://github.com/clowdhaus/terraform-aws-datadog-forwarders - the necessary bucket configuration is provided and the IAM permissions are more finely scoped for only the access necessary based on the configuration you provide

**Comment by tianchu** [comment]
@taiidani Sorry we missed the question from your last reply, do you still facing that issue? Just to clarify, some enhanced metrics are generated by the Forwarder, while the others are generated by the Datadog Lambda library which needs to be installed to your instrumented Lambda functions. That's probably why "Enhanced Metrics" wasn't checked on your screenshot. https://docs.datadoghq.com/serverless/installation/python/?tab=custom

Closing this issue since the original problem has been resolved.
