### ISSUE TITLE
apikey length error when using secretmanager

### ISSUE THREAD

**Issue by wangzz2019** [DataDog/datadog-serverless-functions#375]
**Describe what happened:**
have got this error when using secretmanger
`
[ERROR] Exception: The API key is not the expected length. Please confirm that your API key is correctTraceback (most recent call last):  File "/var/lang/lib/python3.7/imp.py", line 234, in load_module    return load_source(name, filename, file)  File "/var/lang/lib/python3.7/imp.py", line 171, in load_source    module = _load(spec)  File "<frozen importlib._bootstrap>", line 696, in _load  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 728, in exec_module  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed  File "/var/task/lambda_function.py", line 79, in <module>    "The API key is not the expected length. " | [ERROR] Exception: The API key is not the expected length. Please confirm that your API key is correct Traceback (most recent call last):   File "/var/lang/lib/python3.7/imp.py", line 234, in load_module     return load_source(name, filename, file)   File "/var/lang/lib/python3.7/imp.py", line 171, in load_source     module = _load(spec)   File "<frozen importlib._bootstrap>", line 696, in _load   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 728, in exec_module   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed   File "/var/task/lambda_function.py", line 79, in <module>     "The API key is not the expected length. "
-- | --

`

**Describe what you expected:**

**Steps to reproduce the issue:**

1. Save the dd apikey in secret manager first
2. Configure DD_API_KEY_SECRET_ARN
3. Set secretsmanager:GetSecretValue permission

**Comment by tianchu** [comment]
Closing this one to keep the discussion in https://github.com/DataDog/datadog-serverless-functions/pull/376
