### ISSUE TITLE
[Feature Request] Filter Lambda log groups

### ISSUE THREAD

**Issue by GwonsooLee** [DataDog/datadog-serverless-functions#395]
**Describe what happened:**
Currently, if I enabled Lambda Cloudwatch Logs in AWS Integration, then I think it calls lambda forwarder to send logs to  datadog for every lambda log group(probably `/aws/lambda` prefix)

If this is right, then it means that I cannot filter the lambda function, even with name.. 
I can do this by choosing cloudwatch log group in the trigger section in Lambda, but it is hard to add all lambda log group...

**Describe what you expected:**
It would be great If there is any feature with which we can filter log groups in the code. Even filtering with name would be enough ( Tag would be better but then it needs to call api to gather tags..)
If this is possible, then os environment could be the best choice. 
For example, 
DD_EXCLUDE = *-dev
(or)
DD_INCLUDE = *-prod

Then we can filter before sending logs

If there is the way I can use right now but I don't know, then please let me know :)

**Comment by tianchu** [comment]
@GwonsooLee Thanks for submitting the feature request! We do have a way to exclude Lambda functions from collecting CW metrics (e.g., `aws.lambda.invocations`) using tags so they are not billed by Datadog. We are considering to expand that same filter to cover logs as well. Do you think that would work for you? In other words, it will be all or nothing (i.e., ONE filter controlling both metrics AND logs ingestion).

**Comment by GwonsooLee** [comment]
@tianchu Does it have to be filtered at the same time? I prefer if I can set filters for log ingestion differently, but if filtering metrics tags could be applied to logs, it is also okay for me. 

The reason why I want them to be separated(not "all or nothing") is that, for some functions, I want to check error rates so that we can get notification about that. But it is not a critical part so that I don't want to gather logs in datadog(or maybe in order to reduce the cost). 

I want to know how Datadog is  planning to support this filter in the future and ( if possible) when we could use :)

**Comment by tianchu** [comment]
We have a ticket tracking this FR internally, will keep this thread posted for updates.

Just throwing another option out there, if your main concern is the cost, you could probably leverage [Logging without Limits](https://www.datadoghq.com/blog/logging-without-limits/), and exclude those lambda function logs from being indexed within the Datadog platform -- those logs will still be available in live tail mode, but only charged for a much lower **ingest** [price](https://www.datadoghq.com/pricing/?product=log-management#log-management).

**Comment by GwonsooLee** [comment]
I hope this feature comes out as soon as possible~   
Thank you so much for your information @tianchu  👍

(I think I rather add some code on my own until this feature is available~)

**Comment by agocs** [comment]
SLS-795

**Comment by agocs** [comment]
SLS-855

**Comment by tianchu** [comment]
Closing the issue, because the recommended approach for collecting telemetry (including logs) from Lambda functions is now using the Datadog Lambda extension, which can be installed and enabled on a function-by-function basis. Therefore we decided to not work on this FR.
