### ISSUE TITLE
[VPC] Flow logs function is not workig

### ISSUE THREAD

**Issue by anesmashnyi-godaddy** [DataDog/datadog-serverless-functions#410]
**Describe what happened:**
Datadog-VPC-Flow-Logs AWS lambda fails when deployed. Errors from lambda logs:
`module initialization error
An error occurred (InvalidCiphertextException) when calling the Decrypt operation: ` 

**Describe what you expected:**
Working module

**Steps to reproduce the issue:**
I fixed the issue by
1. replacing
`datadog_keys = json.loads(kms.decrypt(CiphertextBlob=b64decode(KMS_ENCRYPTED_KEYS))['Plaintext'])`
with
`datadog_keys = json.loads(kms.decrypt(
    CiphertextBlob=b64decode(KMS_ENCRYPTED_KEYS),
    EncryptionContext={'LambdaFunctionName': os.environ['AWS_LAMBDA_FUNCTION_NAME']}
)['Plaintext'])`

2. Also I use 
`{"api_key":"<API KEY>", "app_key":"<APP KEY>"}`
instead of the line in documentation
`'{"api_key":"<API KEY>", "app_key":"<APP KEY>"}'`

Could you please fix the issue? I'd also suggest to migrate to Python 3.X (2.7 is not supported anymore) 

Cleers,
Aleks.

**Comment by thieman** [comment]
EncryptionContext support is added by #417 which is included in release 1.3.0. Please let us know if you have any other issues.
