### ISSUE TITLE
deploy specific version of datadog-cloudformation-template

### ISSUE THREAD

**Issue by diepes** [DataDog/datadog-serverless-functions#413]
**Describe what happened:**
In the example the Lambda is deployed using 
template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/**latest.yaml**"

Would be great if latest.yaml, **could also be** e.g. **aws-dd-forwarder-3.28.0.yaml**

**Describe what you expected:**
Could specific versions be specified ?  
I could not find any reference on the release page 
https://github.com/DataDog/datadog-serverless-functions/releases

**Steps to reproduce the issue:**

**Comment by tianchu** [comment]
@diepes Yes, actually you can. It's not documented in a prominent way, but see here https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#upgrade-to-a-new-version. You can simply replace `latest.yaml` with `3.28.0.yaml` for instance.
