### ISSUE TITLE
AWS deprecates `botocore.requests` library for Python runtimes

### ISSUE THREAD

**Issue by koszcz** [DataDog/datadog-serverless-functions#422]
I just got a message from AWS:

> Hello,
 We are contacting you regarding actions needed on your account(s) to prevent disruption to your CloudFormation stacks. Starting on April 01, 2021, AWS Lambda will no longer support the botocore.requests library in Python runtimes [1][2]. If you are using the cfn-response module for a Lambda-backed custom resource, you must modify your Lambda function resource's Code or Runtime property and update your stack(s) in order to get the latest version of the cfn-response module which removed its dependency on botocore.requests. If you do not update your Lambda function by April 01, 2021, you will no longer be able to create, update or delete your custom resource. If you are updating the Runtime property, please include the lambda:UpdateFunctionCode action in your IAM policy. If you are hosting your Lambda function code from an S3 bucket, you can refer to the updated cfn-response module's source code in our documentation [3]. For more information on how to update lambda function can be found in knowledge center [4]. Please contact AWS Support if you have any questions or concerns [5]. 

I have little knowledge about Python and Lambda but i see that datadog lamba function is using this library. 
Not sure if this function will stop working after 1st April 2021 or not.

Can someone help me verify it?

**Comment by tianchu** [comment]
@koszcz I assume by "this function" you meant the [AWS Log Forwarder](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring)? If so, make sure your forwarder version is above `v2.3.2` (pretty old).

**Comment by koszcz** [comment]
@tianchu Thank you! Yes, it's AWS Log Forwarder.

**Comment by yukin01** [comment]
@tianchu 
I'm using v3.83.3 and I got the same message.
It is assumed that the following code is being detected.
https://github.com/DataDog/datadog-serverless-functions/blob/aws-dd-forwarder-3.28.3/aws/logs_monitoring/lambda_function.py#L67-L75

Since the requests module is erased from the AWS SDK used in the lambda runtime, I think this code should also be removed, what do you think?

**Comment by tianchu** [comment]
@yukin01 good call, that's probably that's how AWS detected it. Let me remove that code.

**Comment by tianchu** [comment]
https://github.com/DataDog/datadog-serverless-functions/pull/424
