### ISSUE TITLE
[Flow Logs] error: invalid literal for int() with base 10: '-': ValueError

### ISSUE THREAD

**Issue by mikerkeating** [DataDog/datadog-serverless-functions#43]
context

- [Datadog-VPC-Flow-Logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:464622532012:applications~Datadog-VPC-Flow-Logs) deployed from https://serverlessrepo.aws.amazon.com/ on Sunday 3rd June
- code not modified; using keys via KMS
- 2/3 of events processed successfully; 1/3 show error with log message below

error

```
invalid literal for int() with base 10: '-': ValueError
Traceback (most recent call last):
File "/var/task/lambda_function.py", line 337, in lambda_handler
process_message(message, tags, timestamp, node_ip)
File "/var/task/lambda_function.py", line 53, in process_message
process_packets(packets, detailed_tags, timestamp)
File "/var/task/lambda_function.py", line 231, in process_packets
stats.histogram("packets.per_request", int(packets), tags=tags, timestamp=timestamp)
ValueError: invalid literal for int() with base 10: '-'
```

metrics

![screen shot 2018-06-04 at 09 03 53](https://user-images.githubusercontent.com/690583/40905550-3a2db524-67d6-11e8-9bc0-2d5a55843996.png)

**Comment by chrono** [comment]
we're seeing the same error

**Comment by tmichelet** [comment]
Thanks for reporting! We will have a look shortly

**Comment by antimius** [comment]
Also seeing this.

**Comment by garnermccloud** [comment]
Thanks for your patience on this. We'll be working on a fix soon.

**Comment by hobbsh** [comment]
@garnermccloud Any update on this? thanks

**Comment by garnermccloud** [comment]
Thanks for your patience. This has been deployed in the latest version of the application.
