### ISSUE TITLE
[Bug] Not every cloudwatch message is passed

### ISSUE THREAD

**Issue by radekl** [DataDog/datadog-serverless-functions#462]
**Describe what happened:**
We have noticed that for very very long messages that are stored in Cloudwatch, log forwarder is not passing all of them.

I have done some tests and found that Cloudwatch is automatically splitting longer lines to the size of 262119 characters. the maximum that logs forwarder is accepting is 256000 which causes some of logs to be dropped.

The difference is not big and actually changing the DatadogBatcher `max_log_size_bytes` parameter to 265000 did the trick. And all logs from Cloudwatch was passed further.

I'm not sure if there are any other consequences of this change.

**Describe what you expected:**

All entries stored in Cloudwatch should be passed to Datadog.

**Steps to reproduce the issue:**

Create a log entry in Cloudwatch that is between 256000 and 262119 characters.

**Comment by agocs** [comment]
SLS-1248

**Comment by tianchu** [comment]
@radekl thanks for reporting this issue and the experiments you have done. I think it's OK to raise the limit, but I'm confirming it with our log intake experts. BTW, how did you find `Cloudwatch is automatically splitting longer lines to the size of 262119 characters`? From your own tests?

**Comment by radekl** [comment]
After a while we have found that not all the logs are hitting Datadog. It was also quite hard to find why - datadog lambdas weren’t throwing any errors. Although after we found out that the issue is with such extremely long logs, then I’ve started to do some tests with both cloud watch and datadog lambda. The exact number was kind of a manual finding in the end.

**Comment by tianchu** [comment]
@radekl Thanks for letting us know, I'm going to do some experiment too. Really appreciate your feedback!

**Comment by tianchu** [comment]
I can reproduce it and apparently CloudWatch logs' documented event size limit is 256K, but in reality it's 262,144 (can be found when attempting to create a big event in the CW logs console). After discussion with our logs intake team, it is safe to bump the event size limit. Considering the metadata and other overhead, I will bump the limit to 512K (the backend limit is 1M).
