### ISSUE TITLE
Serverless VPC Python Lambda Function - simplified access to SSM Parameters

### ISSUE THREAD

**Issue by ptzulily** [DataDog/datadog-serverless-functions#468]
**Describe what happened:**
Instead of using kms in a somewhat complicated manner to get the api/app keys, they can be pulled simply from existing SSM parameter store and two variables with the paths of the parameter store variables

**Describe what you expected:**
SImple reading from SSM parameter store

**Steps to reproduce the issue:**
Code that is tested and working in production. The ```DD_API_KEY_SSM_NAME``` and ```DD_APPLICATION_KEY_SSM_NAME``` environment variables simply need to be the paths in SSM Parameter Store.
```
ssm_client = boto3.client('ssm')

DD_API_KEY_SSM_NAME = os.getenv("DD_API_KEY_SSM_NAME", default="")
DD_APPLICATION_KEY_SSM_NAME = os.getenv("DD_APPLICATION_KEY_SSM_NAME", default="")

api_key = ssm_client.get_parameter(Name=DD_API_KEY_SSM_NAME, WithDecryption=True)
app_key = ssm_client.get_parameter(Name=DD_APPLICATION_KEY_SSM_NAME, WithDecryption=True)

datadog_keys = {
    "api_key": api_key['Parameter']['Value'],
    "app_key": app_key['Parameter']['Value']
}
```

**Comment by RaphaelAllier** [comment]
Hello,

Closing this issue as it seems it's already implemented. We currently support KMS/SSM/secretsmanager for API key retrieval
