### ISSUE TITLE
aws-dd-forwarder-3.38.0: Update fails with lambda:GetLayerVersion AccessDenied error

### ISSUE THREAD

**Issue by martinlindner** [DataDog/datadog-serverless-functions#493]
**Describe what happened:**
When trying to update  datadog-forwarder stack 3.31.0 -> 3.38.0 in `ap-northeast-1`, the `Forwarder` resource update fails with the following error and triggers a rollback:
```
Resource handler returned message: "User: arn:aws:sts::<redacted> is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ap-northeast-1:464622532012:layer:Datadog-Forwarder:6 (Service: Lambda, Status Code: 403, Request ID: <redacted>, Extended Request ID: null)" (RequestToken: <redacted>, HandlerErrorCode: AccessDenied)
```

Updating 3.31.0 -> 3.37.0 in the same environment worked as expected.

**Describe what you expected:**
Successful update to 3.38.0.

**Steps to reproduce the issue:**
Try to update datadog-forwarder stack with `https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.38.0.yaml`.

**Comment by tianchu** [comment]
@martinlindner I can reproduce this issue and it appears to be a problem with the lambda layer not correctly published to all the regions. For now, you can workaround the issue by setting `InstallAsLayer` to `false`.

**Comment by martinlindner** [comment]
Hi @tianchu, thanks for the quick reponse.

I can confirm that the `InstallAsLayer = false` workaround does the trick for me. I'm perfectly happy with the "legacy" install flow for now, but just FYI, the layer-based installation is still borked in `ap-northeast-1` as of ~15m ago.

**Comment by tianchu** [comment]
@martinlindner good to hear that the workaround worked for you! We are still looking into the layer publishing issue on our side, will keep the issue open until we find a perfect solution for everyone.

**Comment by tianchu** [comment]
@martinlindner we increased the timeout setting on AWS CLI and republished the missing layers, I can now successfully install the Forwarder in Tokyo. Thanks for reporting the issue! 🙇
