### ISSUE TITLE
Datadog Forwarder support for CloudFront Function

### ISSUE THREAD

**Issue by akleiber** [DataDog/datadog-serverless-functions#496]
**Describe what happened:**

Datadog Forwarder can not parse custom metrics logged to CloudWatch by a CloudFront Function.
Instead it forwards the logs.
The reason is that a CloudFront Function always prefixes a log entry with the request id.

```
U7b4hR_RaxMADupvKAvr8_m9gsGXvioUggLV5Oyq-vmAtH8HADpjhw== START DistributionID: E3E5D42GADAXZZ
U7b4hR_RaxMADupvKAvr8_m9gsGXvioUggLV5Oyq-vmAtH8HADpjhw== {"m": "coffee_house.order_value","v": 12.45,"e": 1572273854,"t": ["product:latte", "order:online"]}
U7b4hR_RaxMADupvKAvr8_m9gsGXvioUggLV5Oyq-vmAtH8HADpjhw== END
```

See [AWS Docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-functions.html#monitoring-functions-logs)

**Describe what you expected:**

Datadog Forwarder detects custom metrics from CloudFront Function logs.

**Steps to reproduce the issue:**

- setup CloudFront and add a CloudFront Function either as viewerRequest or viewerResponse
  - see [this tutorial](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/functions-tutorial.html)
- log datadog metric via the function

```
console.log({
    "m": "coffee_house.order_value",
    "v": 12.45,
    "e": 1572273854,
    "t": ["product:latte", "order:online"]
})
```
- subscribe your datadog forwarder Lambda to the loggroup of the CloudFront Function
- call your CDN url to trigger the function

**Possible solution**

- add parser for CloudFront Function logs that removes the CloudFront Function requestid prefix and now can parse the message as JSON

**Comment by tianchu** [comment]
@akleiber Thanks for flagging this, indeed this would be a useful feature! However, we couldn't yet find capacity to work on this, and I would leave the issue open for a while and see if anyone is interested in contributing.

The current recommended solution to submit custom metrics from CloudFront functions is using the logs-> metrics feature https://docs.datadoghq.com/logs/log_configuration/logs_to_metrics/. Do you mind giving it a shot?

**Comment by tianchu** [comment]
@akleiber I'm closing this issue because the lack of interests from the rest of the community. Better support for CloudFront functions is on our long-term roadmap, just need to see more interests from customers. Thank you for flagging this 🙇

**Comment by akleiber** [comment]
Hm yeah that is what we actually tried and failed, because because of the prefixed request id. Maybe I am missing something here and you can point to the correct setup of the logs to metrics configuration to parse the logged lines into metrics. 🤷
