### ISSUE TITLE
Print denied object in error log

### ISSUE THREAD

**Issue by djtecha** [DataDog/datadog-serverless-functions#520]
Currently we get these errors in our Lambda from time to time:

`
[ERROR] ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access DeniedTraceback (most recent call last):  File "/var/task/datadog_lambda/wrapper.py", line 124, in __call__    self.response = self.func(event, context, **kwargs)  File "/var/task/lambda_function.py", line 91, in datadog_forwarder    metrics, logs, trace_payloads = split(transform(enrich(parse(event, context))))  File "/var/task/parsing.py", line 90, in parse    return normalize_events(events, metadata)  File "/var/task/parsing.py", line 599, in normalize_events    for event in events:  File "/var/task/parsing.py", line 180, in s3_handler    response = s3.get_object(Bucket=bucket, Key=key)  File "/var/runtime/botocore/client.py", line 386, in _api_call    return self._make_api_call(operation_name, kwargs)  File "/var/runtime/botocore/client.py", line 705, in _make_api_call    raise error_class(parsed_response, operation_name) | [ERROR] ClientError: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied Traceback (most recent call last):   File "/var/task/datadog_lambda/wrapper.py", line 124, in __call__     self.response = self.func(event, context, **kwargs)   File "/var/task/lambda_function.py", line 91, in datadog_forwarder     metrics, logs, trace_payloads = split(transform(enrich(parse(event, context))))   File "/var/task/parsing.py", line 90, in parse     return normalize_events(events, metadata)   File "/var/task/parsing.py", line 599, in normalize_events     for event in events:   File "/var/task/parsing.py", line 180, in s3_handler     response = s3.get_object(Bucket=bucket, Key=key)   File "/var/runtime/botocore/client.py", line 386, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/runtime/botocore/client.py", line 705, in _make_api_call     raise error_class(parsed_response, operation_name)
`

Curious if we get get the python code to also output what bucket and key its getting denied on to help track down the failure. I know I could comb through the cloudtrail logs but that seems excessive vs just printing the bucket and key if possible.

**Comment by tianchu** [comment]
@djtecha You can actually add an env var `DD_LOG_LEVEL` with value `debug` to print out incoming `event` object and other useful information.
