### ISSUE TITLE
ELB ARN is not built correctly when multi-level S3 key prefix is used to store access logs

### ISSUE THREAD

**Issue by vtstanescu** [DataDog/datadog-serverless-functions#524]
**Describe what happened:**
ARN is not built correctly in `parse_service_arn` function when multi-level S3 key prefix (multiple `/` used) is used for storing access logs

**Describe what you expected:**
The ARN for ELBs to be built correctly irrespective of the S3 key prefix.

**Steps to reproduce the issue:**
AWS Account ID: `123456789123`
AWS Region: `us-east-1`
ALB name: `my-alb-name`
S3 key prefix for access logs: `elasticloadbalancing/my-alb-name`

execute the code block for `source == "elb"` from `parsing.parse_service_arn` for a key like:
`elasticloadbalancing/my-alb-name/AWSLogs/123456789123/elasticloadbalancing/us-east-1/2022/02/08/123456789123_elasticloadbalancing_us-east-1_app.my-alb-name.123456789aabcdef_20220208T1127Z_10.0.0.2_1abcdef2.log.gz`
the result will be `arn:aws:elasticloadbalancing:us-east-1:my-alb-name:loadbalancer/app/my-alb-name/123456789aabcdef` instead of `arn:aws:elasticloadbalancing:us-east-1:123456789123:loadbalancer/app/my-alb-name/123456789aabcdef`

**Comment by hghotra** [comment]
Thanks for creating a PR @MindBreakerVictor , left a couple of minor comments, looks great otherwise!
