### ISSUE TITLE
Datadog's lambda log forwarder changes function name to lowercase

### ISSUE THREAD

**Issue by arvind-pal** [DataDog/datadog-serverless-functions#530]
**Description**
We implemented manual integration between AWS and Datadog with latest layer and version of lambda for log forwarding. We have multiple log groups that trigger the log forwarder lambda which then pushes logs to Datadog.

It has been observed that logs in Datadog, name of the lambda function its tags are changed to lowercase (For example function name demo-LogFunction changes to demo-logfunction)

**Reproduce Scenario:**

Use Cloudformation to create lambda functions and Datadog Monitors. While creating Datadog monitor query, use  '!Ref <lambda-name>' to get name of the lambda function. This name can be a mixture of small and upper case alphabets. Using '!Ref' eases out manual addition of function name to query and further changes to lambda and Datadog monitor's life cycle is managed by Cloudformation.

**What Happened**

The resultant query (with CamelCase function name) does not work in Datadog. As logs appearing in Datadog has function name in lower case.

**Expectation**

Resultant Query for Datadog monitor (with CamelCase function name) should work and able to search through logs.

Could someone suggest the work around here? How the log or metric based queries can be made case insensitive? or CamelCase format of function names can be preserved in log?

**Comment by RaphaelAllier** [comment]
Hello,

We only support lowercased tags as per our [documentation](https://docs.datadoghq.com/getting_started/tagging/#define-tags), so I don't think the issue you're describing is related to the Forwarder itself.
