### ISSUE TITLE
aws-dd-forwarder-3.43.0: Update fails with lambda:GetLayerVersion AccessDenied error

### ISSUE THREAD

**Issue by rl-michaelbrandeis** [DataDog/datadog-serverless-functions#537]
**Describe what happened:**
When trying to update datadog-forwarder stack it generates this error
```
not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Forwarder:12 because no resource-based policy allows the lambda:GetLayerVersion action
```

**Describe what you expected:**
Successful update

**Steps to reproduce the issue:**
Try to update the forwarder stack

Similar issue was reported in the past, but it looks like the root cause was not addressed

https://github.com/DataDog/datadog-serverless-functions/issues/493

**Comment by gavinclarkeuk** [comment]
Seeing the same issue for eu-west-1 region. Seems that v11 of the lambda layer is accessible, but v12 isn't

**Comment by karlanka** [comment]
Same thing here. 

A temporary workaround if you create it from cloudformation is to specify version:

Works:
`https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.42.0.yaml`

Breaks:
`https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.43.0.yaml`
or
`https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml`

**Comment by DarcyRaynerDD** [comment]
Hi everyone 👋 . There was an error with our v12 deployment of the forwarder. We mistakenly didn't publish the Lambda layer,(where we actually package the forwarder code), with our release. While we work to correct this, we've pulled the v12 release. A new release with the correct code will be available soon.

**Comment by magnetikonline** [comment]
Should be able to close this issue now.

Release here: https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.44.0
