### ISSUE TITLE
Enable cleanup of merged PR branches

### ISSUE THREAD

**Issue by magnetikonline** [DataDog/datadog-serverless-functions#555]
Just a quick one - looking here: https://github.com/DataDog/datadog-serverless-functions/branches/all

Tonnes of merged branches against PRs - might be worthwhile to tick the:

> After pull requests are merged, you can have head branches deleted automatically.

Option under settings to keep things trim. 👍

**Comment by RaphaelAllier** [comment]
Hi,

This option has been enabled for a while, cleaning up this issue
Thanks for the suggestion !

**Comment by magnetikonline** [comment]
Great!
