### ISSUE TITLE
[forwarder] Question: can the same S3 bucket be used across multiple regions ?

### ISSUE THREAD

**Issue by eddycharly** [DataDog/datadog-serverless-functions#568]
I deployed `datadog-forwarder` in a couple of regions.

For this, I created an S3 bucket to help with caching.

Now I'm wondering, shall I create one bucket per region ? Or sharing the same bucket is ok ?

**Comment by warrierr** [comment]
@eddycharly creating a unique bucket per region is required currently, though since this is tedious, we are considering adding support for a single bucket across forwarder functions in the future, but don't have immediate plans for this.

**Comment by eddycharly** [comment]
@warrierr thanks for clearing it out. Not sure if it is mentioned in the docs, it could be useful though.

**Comment by tyrcho** [comment]
@eddycharly this has just been released in https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.106.0
