### ISSUE TITLE
aws-dd-forwarder 3.51.0: Unable to import module 'lambda_function'

### ISSUE THREAD

**Issue by jussisallinen** [DataDog/datadog-serverless-functions#569]
**Describe what happened:**

Updated Lambda function zip from **3.44.0** to **3.51.0** and started getting following error in Lambda logs:
```[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)```

![image](https://user-images.githubusercontent.com/5003639/175323015-b81a734e-0c0c-4328-986f-79871772978d.png)

I'm still receiving CloudWatch metrics if that matters.

**Describe what you expected:**

Working Lambda function with no errors in Lambda S3 logs.

**Steps to reproduce the issue:**

Upgade to *3.51.0* and see Lambda S3 logs.
My configuration defines Python **3.7** as required by Datadog.

**Comment by jvanbrie** [comment]
In the most recent version of the lambda forwarder we upgraded the python version to use Python **3.8**. If you want to use the most recent version you'll have to update the version of the lambda as well.

**Comment by jussisallinen** [comment]
> In the most recent version of the lambda forwarder we upgraded the python version to use Python **3.8**. If you want to use the most recent version you'll have to update the version of the lambda as well.

Well that explains it then! I'll do that and close this one for now.

**Comment by jussisallinen** [comment]
That did it:
![image](https://user-images.githubusercontent.com/5003639/175337290-2afb11b2-93ed-450c-bf84-1f3d8d86f906.png)
