### ISSUE TITLE
DD Forwarder v3.51.0 Lambda Layer Version 19 AccessDeniedException

### ISSUE THREAD

**Issue by olivereri** [DataDog/datadog-serverless-functions#580]
**Describe what happened:**
AWS GovCloud us-gov-west-1

We use this solution to manage the DD Forwarder Cloudformation stack in Terrafrom:
https://github.com/DataDog/cloudformation-template/blob/master/aws/datadog_aws_integration.tf

When updating terraform while pointing the `aws_cloudformation_stack` resource to https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml for the `template_url` parameter causes this CF Stack error:

![image](https://user-images.githubusercontent.com/31904439/177626676-a88f383a-bdd1-400f-b6ee-3cbceb0a28c0.png)

> An error occurred (AccessDeniedException) when calling the GetLayerVersionByArn operation: User: arn:aws-us-gov:iam::ACCOUNTID:user/user.name is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws-us-gov:lambda:us-gov-west-1:002406178527:layer:Datadog-Forwarder:19 because no resource-based policy allows the lambda:GetLayerVersion action

DD Forwarder template version 3.51.0 is configured to use layer version 19. The permissions for this AWS resource might not be configured properly. Since it's been 15 days since that release, we might be doing something wrong though. All the other layer versions less than 19 don't throw an `AccessDeniedException` though.

**Describe what you expected:**
Cloudformation stack completes without error when a Lambda function layer version changes.

**Steps to reproduce the issue:**
Update the CF Stack (latest.yaml) or use the below AWS CLI commands:

Does not work for layer 19:
`aws lambda get-layer-version-by-arn --arn 'arn:aws-us-gov:lambda:us-gov-west-1:002406178527:layer:Datadog-Forwarder:19'`

Does work for layer 18, on version 3.50.0:
`aws lambda get-layer-version-by-arn --arn 'arn:aws-us-gov:lambda:us-gov-west-1:002406178527:layer:Datadog-Forwarder:18'`

**Workaround**
`template_url = "https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.50.0.yaml"`

**Related Issue**
https://github.com/department-of-veterans-affairs/va.gov-cms/issues/9540

**Comment by ceberttylertech** [comment]
I am encountering the same issue as @olivereri when trying to deploy the latest version of the DataDog Forwarder Cloud Formation Stack even when running under a user with full admin access and an in-line policy attached to that user granting explicit "lambda:GetLayerVersion" action to resource "arn:aws-us-gov:lambda:*:002406178527:layer:Datadog-Forwarder:*"


The error message I receive is: 

> Resource handler returned message: "User: arn:aws-us-gov:sts::***/*** is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws-us-gov:lambda:us-gov-west-1:002406178527:layer:Datadog-Forwarder:19 because no resource-based policy allows the lambda:GetLayerVersion action (Service: Lambda, Status Code: 403, Request ID: 8aac50a1-65d0-4f9f-979d-bf019b63bf73)" (RequestToken: 9d9a06e1-b8cb-aeca-139e-e8f2d0dc7f4b, HandlerErrorCode: AccessDenied)

**Comment by olivereri** [comment]
I no longer receive an Access Denied error for layer 19 of the Lambda Function in `us-gov-west-1`.

**Comment by ceberttylertech** [comment]
I have a ticket with DataDog ticket #862091 and can also confirm that this issue has now been resolved. Thank you for taking care of it. Thank you, @olivereri, for adding this issue on GitHub, so I knew it wasn't just our organization having issues.
