### ISSUE TITLE
Cloudtrail KeyError in AWS Lambda Forwader version 3.53.0

### ISSUE THREAD

**Issue by plafleur** [DataDog/datadog-serverless-functions#593]
**Describe what happened:**
After upgrading our Lambda Forwarder to 3.53.0, we started seeing the following error in the Cloudwatch logs for the Lambda Forwarder:

[ERROR] KeyError: 'Records'
Traceback (most recent call last):
  File "/opt/python/datadog_lambda/wrapper.py", line 124, in __call__
    self.response = self.func(event, context, **kwargs)
  File "/opt/python/lambda_function.py", line 92, in datadog_forwarder
    metrics, logs, trace_payloads = split(transform(enrich(parse(event, context))))
  File "/opt/python/parsing.py", line 97, in parse
    return normalize_events(events, metadata)
  File "/opt/python/parsing.py", line 785, in normalize_events
    for event in events:
  File "/opt/python/parsing.py", line 203, in s3_handler
    for event in cloud_trail["Records"]:

We also were no longer seeing Cloudtrail logs being sent to Datadog. Rolling back to 3.52.0 fixed the issue.

**Describe what you expected:**

Cloudtrail logs to continue syncing to Datadog.

**Steps to reproduce the issue:**

Upgrade the Lambda forwarder to 3.53.0. Our Cloudtrail configuration is:
- Organization trail
- Multiregion
- Synced to bucket in same account where the Lambda forwarder is deployed, with S3 trigger on Lambda function

**Comment by woz5999** [comment]
This is affecting us as well.

**Comment by zmotu** [comment]
A fix appears to be merged for this but a patch fix release is not yet available for use. @jvanbrie are you able to trigger a github release so the zip artefacts are available for use in the latest cloudformation template.

**Comment by jvanbrie** [comment]
I just released the fix linked above, thanks for bringing this issue to our attention.
