### ISSUE TITLE
Support Python 3.9 lambda runtime

### ISSUE THREAD

**Issue by internetstaff** [DataDog/datadog-serverless-functions#611]
We're using Datadog Posture Management, which recommends that we run the log forwarder lambda in the latest runtime environment. :)

Attempts to switch 3.59 to Python 3.9 result in:

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_rand' from 'ddtrace.internal' (/var/task/ddtrace/internal/__init__.py)
Traceback (most recent call last):
```

**Comment by RaphaelAllier** [comment]
Hello,

Closing this issue as Python 3.9 support was added earlier this year

**Comment by internetstaff** [comment]
It was? In which version? #684 opened two weeks ago seems to disagree. :)
