### ISSUE TITLE
Unable to download older versions of cloudformation template

### ISSUE THREAD

**Issue by jescholl** [DataDog/datadog-serverless-functions#622]
**Describe what happened:**

I received `403 Forbidden` when attempting to download versions of the cloudformation template other than the latest one.

**Describe what you expected:**
I expected to be able to download older versions of the cloudformation template as the [documentation describes](https://github.com/DataDog/datadog-serverless-functions/blob/bf8892b39278f6420f45b74f942db78fbd0b21e6/aws/logs_monitoring/README.md?plain=1#L126):
```
Update the stack using template https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml. You can also replace latest with a specific version, e.g., 3.0.2.yaml, if needed. Make sure to review the changesets before applying the update.
```

**Steps to reproduce the issue:**

*Note: As of writing this, 3.66.0 is the latest release*

Downloading the latest version is possible either as `latest.yaml` or `3.66.0.yaml`
* `curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml`
* `curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.66.0.yaml`

Downloading older versions returns 403
* `curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.65.0.yaml`
* `curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.64.0.yaml`

The documentation gives the example of downloading `3.0.2.yaml`, but that returns 403 as well.
* `curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.0.2.yaml`

**Comment by RaphaelAllier** [comment]
Hello, 

After double-checking access to the bucket where we publish those templates, you should be able to access any previous release. The `AccessDenied` responses when running the commands on the older versions stem from those version not being accessible at all. Sometimes our deploy process has timeouts and we skip versions / they aren't published correctly
I don't have the full context here, but it seems 3.65.0/3.64.0 were skipped in the [Releases](https://github.com/DataDog/datadog-serverless-functions/releases?page=2)

The documentation also references a version that's not accessible for some reason, I'll make a change to correct that part.
As of writing this message, you can do the following operations:

`curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml` -> points to `3.83.0` and the previous versions are available as well:

`curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.83.0.yaml`
`curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.79.0.yaml`
`curl https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/3.77.0.yaml`
