### ISSUE TITLE
DD_SCRUBBING_RULE doesn't match double-byte characters

### ISSUE THREAD

**Issue by Takashi-kun** [DataDog/datadog-serverless-functions#648]
**Describe what happened:**

`DD_SCRUBBING_RULE` doesn't match double-byte characters expectedly.
Following rules work well at the test script, but it doesn't work in Lambda function datadog-forwarder.
```python
import os
import re

def get_env_var(envvar, default, boolean=False):
    value = os.getenv(envvar, default=default)
    if boolean:
        value = value.lower() == "true"
    return value


def compileRegex(rule, pattern):
    if pattern is not None:
        if pattern == "":
            raise Exception(
                "No pattern provided:\nAdd pattern or remove {} environment variable".format(
                    rule
                )
            )
        try:
            return re.compile(pattern)
        except Exception:
            raise Exception(
                "could not compile {} regex with pattern: {}".format(
                    rule, pattern)
            )


if __name__ == "__main__":
    rule = get_env_var("DD_SCRUBBING_RULE", "")
    c = compileRegex(
        "RULE1", rule
    )
    msg = 'あいうえお'
    print(msg)
    print(c.sub('xxx', msg))
```

```console
export DD_SCRUBBING_RULE='[^\u0000-\u007F]+'
$ python test.py                              
あいうえお
xxx
```

**Describe what you expected:**

We want scrub double-bytes character by DD_SCRUBBING_RULE

**Steps to reproduce the issue:**

1. Set `DD_SCRUBBING_RULE` as following rules:
    - `[\u0000-\u007F]+`
    - `[\x01-\x7E\xA1-\xDF]+`
    - `\\[u3000-u303F|u3040-u309F|u30A0-u30FF|uFF00-uFFEF|u4E00-u9FAF]+`
2. Output double-bytes characters to CloudWatch Logs

**Comment by RaphaelAllier** [comment]
Hello,

Closing this issue as this [PR](https://github.com/DataDog/datadog-serverless-functions/pull/676) addresses it
