### ISSUE TITLE
DD_API_KEY_SECRET_ARN is not an ARN

### ISSUE THREAD

**Issue by pauldraper** [DataDog/datadog-serverless-functions#654]
DD_API_KEY_SECRET_ARN is expected to be the secret ID, not the ARN.

Using an ARN produces an error.

**Comment by agocs** [comment]
What error do you see?

**Comment by pauldraper** [comment]
Oops, I had a copy-paste error for the ARN, and the boto3 SDK gives a misleading error about the secret ID.
