### ISSUE TITLE
Forwarder: Tagging logs with the proper `service`

### ISSUE THREAD

**Issue by timmhirsens** [DataDog/datadog-serverless-functions#660]
**Describe what happened:**
In our Java (Spring Boot) we do log in the logstash json format to cloudwatch and would like to forward those to datadog.
The logs are injected with the `dd.env` and `dd.service` tags. However the `service` tag is overriden with `service:cloudwatch`. This means that we do not have proper correlation in APM.

**Describe what you expected:**
The logs should be tagged with the original `dd.service` tag.

**Steps to reproduce the issue:**
1. Run a spring boot application on ECS and log to Cloudwatch
2. use logback-logstash-encoder to log in the logstash json format
3. use the datadog java agent to inject the tags (`DD_LOGS_INJECTION:true`)
4. use the datadog-forwarder to forward the cloudwatch logs to datadog

**Comment by timmhirsens** [comment]
Managed to workaround this with a Service Remapper. I assume that this is the proper way?

**Comment by RaphaelAllier** [comment]
Hello @timmhirsens,

The short answer is yes, we prefer using a [Service Remapper](https://docs.datadoghq.com/logs/log_configuration/processors/?tab=ui#service-remapper) for those particular use cases as we try to keep the forwarder logic as generic as possible

**Comment by jeremytbrun** [comment]
@timmhirsens I know this is an old issue but I'm in a somewhat similar boat you were in. I'm using the Azure Function in this repo to forward logs to Datadog. Within the body of log there is dd.service specified. But it's not a parsed as a tag I can use to remap with the service remapper. Any suggestions?
