### ISSUE TITLE
Lambda log forwarder - changed AWS Lambda enhanced metrics publish behaviour

### ISSUE THREAD

**Issue by magnetikonline** [DataDog/datadog-serverless-functions#679]
**Describe what happened:**

In reference to #677 

@RaphaelAllier / @sabiurr - I feel this is now a **change of behaviour** from the default - since the default setting for `DD_ENHANCED_METRICS` within the CloudFormation template is `false` - and there is no parameter/option to flip it `true`.

https://github.com/DataDog/datadog-serverless-functions/blob/55206a55999fa971aa1ac638a1f9fd0c0c20013b/aws/logs_monitoring/template.yaml#L489

Unless I'm reading this wrong - this means now that anyone deploying https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.76.0 will have enhanced Lambda metrics vanish - as they will no longer be publishing. Thus a change to the previous behaviour.

The fix really has to be either:

- Set `DD_ENHANCED_METRICS: "true"` in the CloudFormation.
- Add a CloudFormation argument to toggle `DD_ENHANCED_METRICS` - with the default being `True`.

As of right now - the https://github.com/DataDog/datadog-serverless-functions/releases/tag/aws-dd-forwarder-3.76.0 is somewhat broken and wouldn't recommend using it.

**Describe what you expected:**

AWS Lambda enhanced metrics continue to be published.

**Steps to reproduce the issue:**

N/A

**Comment by RaphaelAllier** [comment]
Hello @magnetikonline 
Thank you for raising this and contributing !
We had an on-going freeze with our annual convention DASH, hence the delay to release a fix

**Comment by magnetikonline** [comment]
No dramas @RaphaelAllier 👍 - I did feel this one was pretty serious, as it might have caused some unknown pain for users that jumped on this new version right away.
