### ISSUE TITLE
problem with api key length

### ISSUE THREAD

**Issue by Canueto** [DataDog/datadog-serverless-functions#695]
**Describe what happened:**
Hello, I'm in the process of updating to version 3.83 of the AWS application using the latest template.yml file. Everything is fine during this update. However, when it comes to the logging process in the Lambda function, I am encountering errors related to the API key length. The lambda_function.py expects an API key with a length of 32 characters, but in my DataDog account, I can only find API keys with a length of 33 characters.

is a bug?

am doing something bad ?

**Comment by RaphaelAllier** [comment]
Hello,

Which solution/service are you using to store you API KEY (e.g. SecretsManager, KMS, SSM, etc.) ?
We did change the KMS API key decoding recently, but it should impact the length of the key itself

**Comment by Canueto** [comment]
Hello,
Im using SecretsManager. 
At the beginning of the update process with the YAML file, the API KEY I was using got deleted, so I created a new one because I noticed an error in the logs indicating that the key was required.

**Comment by RaphaelAllier** [comment]
Hello,
Since the SecretsManager approach needs the secret ARN, I find it strange that the underlying secret (API key) would change length when upgrading.
I'd recommend opening a ticket on our [support platform ](https://www.datadoghq.com/support/)to investigate this further

**Comment by Canueto** [comment]
[SOLVED]
My mistake, in the update form, I was setting the ARN of the secret; I should have left it as the default value.

@RaphaelAllier thank you for your time
