### ISSUE TITLE
Please use github releases

### ISSUE THREAD

**Issue by zboni-gpsw** [DataDog/datadog-serverless-functions#70]
It would be great if you guys could post lambda function updates with a new git tag or release, so that we can detect it and automagically pull down the latest code into our environment. Thanks!

**Comment by inductor** [comment]
Seems like release is not used 🤔

**Comment by NilsBunge** [comment]
This is indeed not yet available but we are working on it as we are planning an important change for the Lambda forwarder.

Sorry for the delay on this, we know this is something important and we definitely have not forgotten about it.

**Comment by FnTm** [comment]
Looks like releases are being used now. Could this issue be a prime candidate for 🧹?

**Comment by pinkerton** [comment]
We've moved to using GitHub releases - going to close this!
