### ISSUE TITLE
Add new region `ca-west-1` to Datadog-Forwarder layer

### ISSUE THREAD

**Issue by weizhangfd** [DataDog/datadog-serverless-functions#735]
**Describe what happened:**
Hello! We use `https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml` as the template for creating the datadog forwarder. But when trying to deploy it to the new Calgary region `ca-west-1`, I ran into the following error
```
User: arn:aws:sts::<targeted-account-number>:assumed-role/<some-role-name> is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:ca-west-1:464622532012:layer:Datadog-Forwarder:44 because no resource-based policy allows the lambda:GetLayerVersion action
```

Please could you help add support to the new region? I saw there is a script to add new region https://github.com/DataDog/datadog-serverless-functions/blob/master/aws/logs_monitoring/tools/add_new_region.sh, so happy to contribute to this if you could provide me some guidance too. Many thanks!

**Describe what you expected:**

Able to deploy the cloudformation stack in ca-west-1 like in other regions we have done.

**Steps to reproduce the issue:**
Deploy the cloudformation stack using `https://datadog-cloudformation-template.s3.amazonaws.com/aws/forwarder/latest.yaml` as template to region `ca-west-1`

**Comment by RaphaelAllier** [comment]
Hey @weizhangfd, we published the layers in the new regions so using the latest template you should not encounter any issues anymore deploying the Forwarder to the `il-central-1` or `ca-west-1` regions.

Closing this issue, feel free to ping me if you any other problems
