### ISSUE TITLE
AWS S3 Securityhub finding about target access-logs bucket not configured

### ISSUE THREAD

**Issue by xnick123** [DataDog/datadog-serverless-functions#764]
**Describe what happened:**

AWS Securityhub create "noise" by flagging the missing configuration of a target access-log bucket not being configured. I propose to add it as configurable parameter, to allow the user to provide one if needed.

In enterprises you often want all access to S3 being logged, S3 buckets allow to define a target access-log bucket for that. 
I expect this to be affecting all AWS customers using Security Hub. The workaround to ignore it, or put it to resolved, is not practical for dynamic environments. Hence it would be a small but useful product improvement to add the ability for the customer/user to decide.

_[S3.9] This control checks whether server access logging is enabled for an Amazon S3 general purpose bucket. The control fails if server access logging isn't enabled. When logging is enabled, Amazon S3 delivers access logs for a source bucket to a chosen target bucket. The target bucket must be in the same AWS Region as the source bucket and must not have a default retention period configured. The target logging bucket does not need to have server access logging enabled, and you should suppress findings for this bucket._ 

![image](https://github.com/DataDog/datadog-serverless-functions/assets/19893697/f17fcb31-5bbd-4dd2-ba2d-3ef3fda87efc)

**Describe what you expected:**
This security finding to disappear be resolved. 

**Steps to reproduce the issue:**

1. In the AWS Console go to the "Security Hub" Service
2. Select Controls and S3.9
3. Find the Datadog forwarder bucket

**Comment by xnick123** [comment]
Hi @ge0Aja, this one is similar and based on Request #1665783. I had issues rebasing and created a new branch with the addition, due to conflicts with a prior change.

**Comment by ViBiOh** [comment]
Hi @xnick123,

Sorry for the late reply, I tested you template and everything seems fine. ~Do you mind reopening the pull-request and request-review me?~

Edit: I find [it here](https://github.com/DataDog/datadog-serverless-functions/pull/779) but it has a conflict.
