### ISSUE TITLE
[RDS] MSSQL Metrics causing lambda to fail due to missing keys/metrics

### ISSUE THREAD

**Issue by liamraemclauchlan** [DataDog/datadog-serverless-functions#80]
**Describe what happened:**
If the RDS instance is MSSQL, the RDS lambda is unable to parse the event due to missing keys. 
Examples of these missing keys are loadAverageMinute, and processList.id

**Describe what you expected:**
The lambda to parse events regardless of RDS engine.

**Steps to reproduce the issue:**
Process event from RDS  Engine: SqlServer
`{
    "engine": "SqlServer",
    "instanceID": "instanceID",
    "instanceResourceID": "db-resourceID",
    "timestamp": "2019-01-15T14:48:12Z",
    "version": 1,
    "uptime": "118 days, 04:25:12",
    "numVCPUs": 4,
    "cpuUtilization": {
        "idle": 99.22,
        "kern": 0.29,
        "user": 0.49
    },
    "memory": {
        "commitTotKb": 5907972,
        "commitLimitKb": 17301104,
        "commitPeakKb": 6611268,
        "physTotKb": 16776816,
        "physAvailKb": 11120468,
        "sysCacheKb": 8085436,
        "kernTotKb": 309488,
        "kernPagedKb": 212980,
        "kernNonpagedKb": 96508,
        "sqlServerTotKb": 4117792,
        "pageSize": 4096
    },
    "system": {
        "handles": 18148,
        "threads": 754,
        "processes": 41
    },
    "disks": [
        {
            "name": "rdsdbdata",
            "totalKb": 31324096,
            "usedKb": 1238528,
            "usedPc": 3.95,
            "availKb": 30085568,
            "availPc": 96.05,
            "rdCountPS": 0,
            "rdBytesPS": 0,
            "wrCountPS": 0.6,
            "wrBytesPS": 2286.93
        }
    ],
    "network": [
        {
            "interface": "Ethernet 4",
            "rdBytesPS": 35552.47,
            "wrBytesPS": 26602.47
        }
    ],
    "processList": [
        {
            "name": "OS processes",
            "cpuUsedPc": 0,
            "memUsedPc": 0.66,
            "workingSetKb": 280000,
            "workingSetPrivKb": 110228,
            "workingSetShareableKb": 169772,
            "virtKb": 53690518976
        },
        {
            "name": "RDS processes",
            "cpuUsedPc": 0.18,
            "memUsedPc": 1.87,
            "workingSetKb": 437872,
            "workingSetPrivKb": 314516,
            "workingSetShareableKb": 123356,
            "virtKb": 2183729268
        }
]`

**Comment by liamraemclauchlan** [comment]
'loadAverageMinute': KeyError
Traceback (most recent call last):
File "/var/task/datadog-rds-collector.py", line 132, in lambda_handler
_process_rds_enhanced_monitoring_message(ts, message, account, region)
File "/var/task/datadog-rds-collector.py", line 55, in _process_rds_enhanced_monitoring_message
'aws.rds.load.1', message["loadAverageMinute"]["one"],
KeyError: 'loadAverageMinute'

**Comment by DanielLanger** [comment]
hi @liamraemclauchlan can you please email me with the email you use for Datadog at daniel.langer@datadoghq.com so we can dig into this further? Thanks!

**Comment by garnermccloud** [comment]
Thanks for your patience. This has been deployed in the latest version of the application.
